#define _CRT_SECURE_NO_WARNINGS

/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "pcan_runtime.h"
/* End BUSMASTER include header */

#define CIA_LU_COUNT 4

#define IDC_APPLY              1001
#define IDC_DEFAULT            1002
#define IDC_AUTO_WAVE          1003
#define IDC_TOPMOST            1004
#define IDC_BC_NODE            1010
#define IDC_SDO_NODE           1011
#define IDC_SINGLE_SDO_NODE    1012
#define IDC_BC_HEARTBEAT       1013
#define IDC_SDO_HEARTBEAT      1014
#define IDC_STATUS             1015
#define IDC_LU_BASE            1100
#define IDC_LU_STRIDE          32
#define IDC_LU_ENABLED         0
#define IDC_LU_READY           1
#define IDC_LU_ACTIVE          2
#define IDC_LU_MOVE            3
#define IDC_LU_WU              4
#define IDC_LU_CU              5
#define IDC_LU_WINDOW          6
#define IDC_LU_BIN             7
#define IDC_LU_POSITION        8
#define IDC_LU_SHORT_COUNTER   9
#define IDC_LU_TOTAL_COUNTER   10

/* Start BUSMASTER global variable */
CRITICAL_SECTION gMsgTxLock;
CRITICAL_SECTION gCiaParamLock;
HANDLE gCiaGuiThread = NULL;
DWORD gCiaGuiThreadId = 0;
HWND gCiaGuiWindow = NULL;
unsigned int gCiaWaveTick = 0;
unsigned char gCiaCluster = 1;
unsigned char gCiaBcNode = 0x0A;
unsigned char gCiaSdoNode = 0x14;
unsigned char gCiaSingleSdoNode = 1;
unsigned char gCiaBcHeartbeatEnabled = 1;
unsigned char gCiaSdoHeartbeatEnabled = 1;
unsigned char gCiaTopmost = 1;
unsigned char gCiaWaveEnabled = 1;
unsigned long gCiaSdoRxCount = 0;
unsigned long gCiaSdoTxCount = 0;
unsigned int gCiaLastSdoRequest = 0;
unsigned int gCiaLastSdoResponse = 0;

typedef struct
{
    unsigned char enabled;
    unsigned char ready;
    unsigned char active;
    unsigned char move;
    unsigned char wu;
    unsigned char cu;
    unsigned char window;
    unsigned char bin;
    unsigned int positionTenth;
    unsigned int shortCounter;
    unsigned long totalCounter;
} CIA_LU_STATE;

CIA_LU_STATE gCiaLu[CIA_LU_COUNT] = {
    {1, 1, 1, 1, 1, 1, 0, 1, 325, 12, 1200},
    {1, 1, 1, 1, 1, 1, 0, 1, 280, 18, 1800},
    {1, 1, 1, 0, 1, 1, 0, 1, 145, 7, 700},
    {1, 1, 1, 0, 1, 1, 0, 1, 95, 4, 400}
};
/* End BUSMASTER global variable */

static void ciaApplyDefaults();
static void ciaRefreshGui(HWND hwnd);
static void ciaApplyGui(HWND hwnd);
static void ciaApplyChecks(HWND hwnd);
static void ciaStartGuiThread();
static void ciaStopGuiThread();
static void ciaSendLuPdos(unsigned char index);
static void ciaSendHeartbeats();
static void ciaUpdateWave();
static void ciaHandleSdoRequest(const STCAN_MSG& rx);

/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnDLL_Load();
GCC_EXTERN void GCC_EXPORT OnDLL_Unload();
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
GCC_EXTERN void GCC_EXPORT OnTimer_CIA422_FAST_100();
GCC_EXTERN void GCC_EXPORT OnTimer_CIA422_HEARTBEAT_1000();
GCC_EXTERN void GCC_EXPORT OnMsg_All(STCAN_MSG RxMsg);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */

static int ciaClampInt(int value, int minValue, int maxValue)
{
    if (value < minValue) return minValue;
    if (value > maxValue) return maxValue;
    return value;
}

static unsigned long ciaClampU32(unsigned long value, unsigned long maxValue)
{
    if (value > maxValue) return maxValue;
    return value;
}

static int ciaWaveValue(unsigned int tick, unsigned int period, int minValue, int maxValue)
{
    unsigned int pos;
    unsigned int half;
    int span;

    if (period < 2)
        return minValue;

    pos = tick % period;
    half = period / 2;
    span = maxValue - minValue;

    if (pos < half)
        return minValue + (int)((span * pos) / half);

    return maxValue - (int)((span * (pos - half)) / (period - half));
}

static unsigned short ciaLuStatusWord(const CIA_LU_STATE& lu)
{
    unsigned short value = 0;

    value |= (unsigned short)(lu.bin & 0x03);
    value |= (unsigned short)((lu.window & 0x03) << 2);
    value |= (unsigned short)((lu.cu & 0x07) << 4);
    value |= (unsigned short)((lu.wu & 0x07) << 7);
    value |= (unsigned short)((lu.move & 0x07) << 10);
    value |= (unsigned short)((lu.active ? 1 : 0) << 14);
    value |= (unsigned short)((lu.ready ? 1 : 0) << 15);
    return value;
}

static void ciaSetU16(unsigned char* data, int index, unsigned int value)
{
    data[index] = (unsigned char)(value & 0xFF);
    data[index + 1] = (unsigned char)((value >> 8) & 0xFF);
}

static void ciaSetU32(unsigned char* data, int index, unsigned long value)
{
    data[index] = (unsigned char)(value & 0xFF);
    data[index + 1] = (unsigned char)((value >> 8) & 0xFF);
    data[index + 2] = (unsigned char)((value >> 16) & 0xFF);
    data[index + 3] = (unsigned char)((value >> 24) & 0xFF);
}

static void ciaSendCanFrame(unsigned int canId, const unsigned char* data, unsigned char dlc)
{
    STCAN_MSG msg(canId, false, dlc, false);
    unsigned char cluster;

    EnterCriticalSection(&gCiaParamLock);
    cluster = gCiaCluster;
    LeaveCriticalSection(&gCiaParamLock);

    msg.cluster = cluster;
    msg.isExtended = false;
    msg.isRtr = false;
    msg.isCanfd = false;
    msg.dlc = dlc;
    for (unsigned int i = 0; i < dlc && i < 8; i++)
        msg.data[i] = data[i];

    EnterCriticalSection(&gMsgTxLock);
    SendMsg(msg);
    LeaveCriticalSection(&gMsgTxLock);
}

static int ciaReadInt(HWND hwnd, int id, int minValue, int maxValue)
{
    char text[32];
    int value;

    GetDlgItemText(hwnd, id, text, sizeof(text));
    value = atoi(text);
    return ciaClampInt(value, minValue, maxValue);
}

static unsigned long ciaReadULong(HWND hwnd, int id, unsigned long maxValue)
{
    char text[32];
    unsigned long value;

    GetDlgItemText(hwnd, id, text, sizeof(text));
    value = strtoul(text, NULL, 10);
    return ciaClampU32(value, maxValue);
}

static void ciaSetInt(HWND hwnd, int id, int value)
{
    char text[32];
    sprintf(text, "%d", value);
    SetDlgItemText(hwnd, id, text);
}

static void ciaSetULong(HWND hwnd, int id, unsigned long value)
{
    char text[32];
    sprintf(text, "%lu", value);
    SetDlgItemText(hwnd, id, text);
}

static void ciaSetCheck(HWND hwnd, int id, unsigned char checked)
{
    SendDlgItemMessage(hwnd, id, BM_SETCHECK, checked ? BST_CHECKED : BST_UNCHECKED, 0);
}

static unsigned char ciaGetCheck(HWND hwnd, int id)
{
    return (SendDlgItemMessage(hwnd, id, BM_GETCHECK, 0, 0) == BST_CHECKED) ? 1 : 0;
}

static void ciaUpdateTopmost(HWND hwnd)
{
    SetWindowPos(hwnd, gCiaTopmost ? HWND_TOPMOST : HWND_NOTOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
}

static int ciaControlId(int index, int field)
{
    return IDC_LU_BASE + index * IDC_LU_STRIDE + field;
}

static void ciaApplyDefaults()
{
    EnterCriticalSection(&gCiaParamLock);
    gCiaBcNode = 0x0A;
    gCiaSdoNode = 0x14;
    gCiaSingleSdoNode = 1;
    gCiaBcHeartbeatEnabled = 1;
    gCiaSdoHeartbeatEnabled = 1;
    for (int i = 0; i < CIA_LU_COUNT; i++)
    {
        gCiaLu[i].enabled = 1;
        gCiaLu[i].ready = 1;
        gCiaLu[i].active = 1;
        gCiaLu[i].move = (i < 2) ? 1 : 0;
        gCiaLu[i].wu = 1;
        gCiaLu[i].cu = 1;
        gCiaLu[i].window = 0;
        gCiaLu[i].bin = 1;
        gCiaLu[i].positionTenth = 100 + (unsigned int)i * 75;
        gCiaLu[i].shortCounter = 10 + (unsigned int)i * 3;
        gCiaLu[i].totalCounter = 1000 + (unsigned long)i * 500;
    }
    LeaveCriticalSection(&gCiaParamLock);
}

static void ciaRefreshGui(HWND hwnd)
{
    CIA_LU_STATE lu[CIA_LU_COUNT];
    unsigned char bcNode;
    unsigned char sdoNode;
    unsigned char singleSdoNode;
    unsigned char bcHeartbeat;
    unsigned char sdoHeartbeat;
    unsigned char waveEnabled;
    unsigned char topmost;
    unsigned long sdoRx;
    unsigned long sdoTx;
    unsigned int lastReq;
    unsigned int lastResp;
    char status[128];

    EnterCriticalSection(&gCiaParamLock);
    bcNode = gCiaBcNode;
    sdoNode = gCiaSdoNode;
    singleSdoNode = gCiaSingleSdoNode;
    bcHeartbeat = gCiaBcHeartbeatEnabled;
    sdoHeartbeat = gCiaSdoHeartbeatEnabled;
    waveEnabled = gCiaWaveEnabled;
    topmost = gCiaTopmost;
    sdoRx = gCiaSdoRxCount;
    sdoTx = gCiaSdoTxCount;
    lastReq = gCiaLastSdoRequest;
    lastResp = gCiaLastSdoResponse;
    memcpy(lu, gCiaLu, sizeof(lu));
    LeaveCriticalSection(&gCiaParamLock);

    ciaSetInt(hwnd, IDC_BC_NODE, bcNode);
    ciaSetInt(hwnd, IDC_SDO_NODE, sdoNode);
    ciaSetCheck(hwnd, IDC_SINGLE_SDO_NODE, singleSdoNode);
    ciaSetCheck(hwnd, IDC_BC_HEARTBEAT, bcHeartbeat);
    ciaSetCheck(hwnd, IDC_SDO_HEARTBEAT, sdoHeartbeat);
    ciaSetCheck(hwnd, IDC_AUTO_WAVE, waveEnabled);
    ciaSetCheck(hwnd, IDC_TOPMOST, topmost);

    for (int i = 0; i < CIA_LU_COUNT; i++)
    {
        ciaSetCheck(hwnd, ciaControlId(i, IDC_LU_ENABLED), lu[i].enabled);
        ciaSetCheck(hwnd, ciaControlId(i, IDC_LU_READY), lu[i].ready);
        ciaSetCheck(hwnd, ciaControlId(i, IDC_LU_ACTIVE), lu[i].active);
        ciaSetInt(hwnd, ciaControlId(i, IDC_LU_MOVE), lu[i].move);
        ciaSetInt(hwnd, ciaControlId(i, IDC_LU_WU), lu[i].wu);
        ciaSetInt(hwnd, ciaControlId(i, IDC_LU_CU), lu[i].cu);
        ciaSetInt(hwnd, ciaControlId(i, IDC_LU_WINDOW), lu[i].window);
        ciaSetInt(hwnd, ciaControlId(i, IDC_LU_BIN), lu[i].bin);
        ciaSetInt(hwnd, ciaControlId(i, IDC_LU_POSITION), lu[i].positionTenth);
        ciaSetInt(hwnd, ciaControlId(i, IDC_LU_SHORT_COUNTER), lu[i].shortCounter);
        ciaSetULong(hwnd, ciaControlId(i, IDC_LU_TOTAL_COUNTER), lu[i].totalCounter);
    }

    sprintf(status, "SDO RX %lu  TX %lu  last %03X -> %03X", sdoRx, sdoTx, lastReq, lastResp);
    SetWindowText(GetDlgItem(hwnd, IDC_STATUS), status);
}

static void ciaApplyGui(HWND hwnd)
{
    EnterCriticalSection(&gCiaParamLock);
    gCiaBcNode = (unsigned char)ciaReadInt(hwnd, IDC_BC_NODE, 1, 127);
    gCiaSdoNode = (unsigned char)ciaReadInt(hwnd, IDC_SDO_NODE, 1, 127);
    gCiaSingleSdoNode = ciaGetCheck(hwnd, IDC_SINGLE_SDO_NODE);
    gCiaBcHeartbeatEnabled = ciaGetCheck(hwnd, IDC_BC_HEARTBEAT);
    gCiaSdoHeartbeatEnabled = ciaGetCheck(hwnd, IDC_SDO_HEARTBEAT);
    gCiaWaveEnabled = ciaGetCheck(hwnd, IDC_AUTO_WAVE);
    gCiaTopmost = ciaGetCheck(hwnd, IDC_TOPMOST);

    for (int i = 0; i < CIA_LU_COUNT; i++)
    {
        gCiaLu[i].enabled = ciaGetCheck(hwnd, ciaControlId(i, IDC_LU_ENABLED));
        gCiaLu[i].ready = ciaGetCheck(hwnd, ciaControlId(i, IDC_LU_READY));
        gCiaLu[i].active = ciaGetCheck(hwnd, ciaControlId(i, IDC_LU_ACTIVE));
        gCiaLu[i].move = (unsigned char)ciaReadInt(hwnd, ciaControlId(i, IDC_LU_MOVE), 0, 7);
        gCiaLu[i].wu = (unsigned char)ciaReadInt(hwnd, ciaControlId(i, IDC_LU_WU), 0, 7);
        gCiaLu[i].cu = (unsigned char)ciaReadInt(hwnd, ciaControlId(i, IDC_LU_CU), 0, 7);
        gCiaLu[i].window = (unsigned char)ciaReadInt(hwnd, ciaControlId(i, IDC_LU_WINDOW), 0, 3);
        gCiaLu[i].bin = (unsigned char)ciaReadInt(hwnd, ciaControlId(i, IDC_LU_BIN), 0, 3);
        gCiaLu[i].positionTenth = (unsigned int)ciaReadInt(hwnd, ciaControlId(i, IDC_LU_POSITION), 0, 1000);
        gCiaLu[i].shortCounter = (unsigned int)ciaReadInt(hwnd, ciaControlId(i, IDC_LU_SHORT_COUNTER), 0, 65535);
        gCiaLu[i].totalCounter = ciaReadULong(hwnd, ciaControlId(i, IDC_LU_TOTAL_COUNTER), 0xFFFFFFFFUL);
    }
    LeaveCriticalSection(&gCiaParamLock);
    ciaUpdateTopmost(hwnd);
}

static int ciaIsCheckControl(int controlId)
{
    return controlId == IDC_AUTO_WAVE ||
           controlId == IDC_TOPMOST ||
           controlId == IDC_SINGLE_SDO_NODE ||
           controlId == IDC_BC_HEARTBEAT ||
           controlId == IDC_SDO_HEARTBEAT ||
           (controlId >= IDC_LU_BASE &&
            controlId < IDC_LU_BASE + CIA_LU_COUNT * IDC_LU_STRIDE &&
            ((controlId - IDC_LU_BASE) % IDC_LU_STRIDE == IDC_LU_ENABLED ||
             (controlId - IDC_LU_BASE) % IDC_LU_STRIDE == IDC_LU_READY ||
             (controlId - IDC_LU_BASE) % IDC_LU_STRIDE == IDC_LU_ACTIVE));
}

static void ciaApplyChecks(HWND hwnd)
{
    EnterCriticalSection(&gCiaParamLock);
    gCiaWaveEnabled = ciaGetCheck(hwnd, IDC_AUTO_WAVE);
    gCiaTopmost = ciaGetCheck(hwnd, IDC_TOPMOST);
    gCiaSingleSdoNode = ciaGetCheck(hwnd, IDC_SINGLE_SDO_NODE);
    gCiaBcHeartbeatEnabled = ciaGetCheck(hwnd, IDC_BC_HEARTBEAT);
    gCiaSdoHeartbeatEnabled = ciaGetCheck(hwnd, IDC_SDO_HEARTBEAT);

    for (int i = 0; i < CIA_LU_COUNT; i++)
    {
        gCiaLu[i].enabled = ciaGetCheck(hwnd, ciaControlId(i, IDC_LU_ENABLED));
        gCiaLu[i].ready = ciaGetCheck(hwnd, ciaControlId(i, IDC_LU_READY));
        gCiaLu[i].active = ciaGetCheck(hwnd, ciaControlId(i, IDC_LU_ACTIVE));
    }
    LeaveCriticalSection(&gCiaParamLock);
    ciaUpdateTopmost(hwnd);
}

static void ciaCreateLabel(HWND hwnd, const char* text, int id, int x, int y, int w, int h)
{
    CreateWindowExA(0, "STATIC", text, WS_CHILD | WS_VISIBLE, x, y, w, h, hwnd, (HMENU)(INT_PTR)id, GetModuleHandle(NULL), NULL);
}

static void ciaCreateEdit(HWND hwnd, int id, int x, int y, int w, int h)
{
    CreateWindowExA(0, "EDIT", "", WS_CHILD | WS_VISIBLE | WS_BORDER | ES_AUTOHSCROLL, x, y, w, h, hwnd, (HMENU)(INT_PTR)id, GetModuleHandle(NULL), NULL);
}

static void ciaCreateCheck(HWND hwnd, const char* text, int id, int x, int y, int w, int h)
{
    CreateWindowExA(0, "BUTTON", text, WS_CHILD | WS_VISIBLE | BS_AUTOCHECKBOX, x, y, w, h, hwnd, (HMENU)(INT_PTR)id, GetModuleHandle(NULL), NULL);
}

static void ciaCreateGuiControls(HWND hwnd)
{
    CreateWindowExA(0, "BUTTON", "Apply", WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON, 16, 14, 78, 26, hwnd, (HMENU)IDC_APPLY, GetModuleHandle(NULL), NULL);
    CreateWindowExA(0, "BUTTON", "Default", WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON, 108, 14, 78, 26, hwnd, (HMENU)IDC_DEFAULT, GetModuleHandle(NULL), NULL);
    ciaCreateCheck(hwnd, "Auto wave", IDC_AUTO_WAVE, 205, 18, 92, 22);
    ciaCreateCheck(hwnd, "Always on top", IDC_TOPMOST, 565, 18, 120, 22);

    CreateWindowExA(0, "BUTTON", "CANopen / Skaut defaults", WS_CHILD | WS_VISIBLE | BS_GROUPBOX, 12, 50, 700, 72, hwnd, NULL, GetModuleHandle(NULL), NULL);
    ciaCreateLabel(hwnd, "BC node", 0, 28, 78, 58, 18);
    ciaCreateEdit(hwnd, IDC_BC_NODE, 88, 74, 44, 22);
    ciaCreateLabel(hwnd, "Counters SDO node", 0, 150, 78, 122, 18);
    ciaCreateEdit(hwnd, IDC_SDO_NODE, 276, 74, 44, 22);
    ciaCreateCheck(hwnd, "Single SDO node for LU counters", IDC_SINGLE_SDO_NODE, 342, 76, 210, 22);
    ciaCreateCheck(hwnd, "BC heartbeat", IDC_BC_HEARTBEAT, 28, 100, 112, 18);
    ciaCreateCheck(hwnd, "SDO node heartbeat", IDC_SDO_HEARTBEAT, 150, 100, 150, 18);

    CreateWindowExA(0, "BUTTON", "LU process data and SDO counters", WS_CHILD | WS_VISIBLE | BS_GROUPBOX, 12, 132, 700, 238, hwnd, NULL, GetModuleHandle(NULL), NULL);
    ciaCreateLabel(hwnd, "LU", 0, 28, 160, 28, 18);
    ciaCreateLabel(hwnd, "EN", 0, 62, 160, 30, 18);
    ciaCreateLabel(hwnd, "Ready", 0, 100, 160, 48, 18);
    ciaCreateLabel(hwnd, "Active", 0, 154, 160, 48, 18);
    ciaCreateLabel(hwnd, "Move", 0, 218, 160, 42, 18);
    ciaCreateLabel(hwnd, "WU", 0, 274, 160, 32, 18);
    ciaCreateLabel(hwnd, "CU", 0, 322, 160, 32, 18);
    ciaCreateLabel(hwnd, "Window", 0, 370, 160, 58, 18);
    ciaCreateLabel(hwnd, "Bin", 0, 438, 160, 36, 18);
    ciaCreateLabel(hwnd, "Position x0.1", 0, 486, 160, 86, 18);
    ciaCreateLabel(hwnd, "Short", 0, 586, 160, 48, 18);
    ciaCreateLabel(hwnd, "Total", 0, 646, 160, 48, 18);

    for (int i = 0; i < CIA_LU_COUNT; i++)
    {
        int y = 184 + i * 38;
        char label[8];
        sprintf(label, "LU%d", i + 1);
        ciaCreateLabel(hwnd, label, 0, 28, y + 3, 34, 18);
        ciaCreateCheck(hwnd, "", ciaControlId(i, IDC_LU_ENABLED), 64, y, 24, 22);
        ciaCreateCheck(hwnd, "", ciaControlId(i, IDC_LU_READY), 112, y, 24, 22);
        ciaCreateCheck(hwnd, "", ciaControlId(i, IDC_LU_ACTIVE), 166, y, 24, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_MOVE), 214, y, 42, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_WU), 270, y, 42, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_CU), 318, y, 42, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_WINDOW), 372, y, 42, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_BIN), 432, y, 42, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_POSITION), 490, y, 76, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_SHORT_COUNTER), 584, y, 52, 22);
        ciaCreateEdit(hwnd, ciaControlId(i, IDC_LU_TOTAL_COUNTER), 644, y, 58, 22);
    }

    CreateWindowExA(0, "BUTTON", "Status", WS_CHILD | WS_VISIBLE | BS_GROUPBOX, 12, 382, 700, 54, hwnd, NULL, GetModuleHandle(NULL), NULL);
    ciaCreateLabel(hwnd, "", IDC_STATUS, 28, 408, 650, 18);
}

static LRESULT CALLBACK ciaGuiWndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    int controlId;
    int notificationCode;

    switch (msg)
    {
        case WM_CREATE:
            ciaCreateGuiControls(hwnd);
            PcanRuntimeCreateControls(hwnd, 12, 444, 700);
            ciaRefreshGui(hwnd);
            ciaUpdateTopmost(hwnd);
            SetTimer(hwnd, 1, 500, NULL);
            return 0;

        case WM_TIMER:
            PcanRuntimeRefreshStatus(hwnd);
            if (gCiaWaveEnabled)
                ciaRefreshGui(hwnd);
            else
            {
                char status[128];
                EnterCriticalSection(&gCiaParamLock);
                sprintf(status, "SDO RX %lu  TX %lu  last %03X -> %03X", gCiaSdoRxCount, gCiaSdoTxCount, gCiaLastSdoRequest, gCiaLastSdoResponse);
                LeaveCriticalSection(&gCiaParamLock);
                SetWindowText(GetDlgItem(hwnd, IDC_STATUS), status);
            }
            return 0;

        case WM_COMMAND:
            controlId = LOWORD(wParam);
            notificationCode = HIWORD(wParam);
            if (PcanRuntimeHandleCommand(hwnd, controlId, notificationCode))
                return 0;
            if (controlId == IDC_APPLY && notificationCode == BN_CLICKED)
            {
                ciaApplyGui(hwnd);
                ciaRefreshGui(hwnd);
                return 0;
            }
            if (controlId == IDC_DEFAULT && notificationCode == BN_CLICKED)
            {
                ciaApplyDefaults();
                ciaRefreshGui(hwnd);
                return 0;
            }
            if (ciaIsCheckControl(controlId) && notificationCode == BN_CLICKED)
            {
                ciaApplyChecks(hwnd);
                ciaRefreshGui(hwnd);
                return 0;
            }
            break;

        case WM_CLOSE:
            DestroyWindow(hwnd);
            return 0;

        case WM_DESTROY:
            KillTimer(hwnd, 1);
            gCiaGuiWindow = NULL;
            PostQuitMessage(0);
            return 0;
    }
    return DefWindowProc(hwnd, msg, wParam, lParam);
}

static DWORD WINAPI ciaGuiThreadProc(LPVOID)
{
    WNDCLASSA wc;
    HWND hwnd;
    MSG msg;

    memset(&wc, 0, sizeof(wc));
    wc.lpfnWndProc = ciaGuiWndProc;
    wc.hInstance = GetModuleHandle(NULL);
    wc.lpszClassName = "CleanOpenEmulatorWindow";
    wc.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    RegisterClassA(&wc);

    hwnd = CreateWindowExA(WS_EX_TOPMOST, wc.lpszClassName, "PCAN CANopen Emulator", WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX,
                          0, 0, 742, 575, NULL, NULL, wc.hInstance, NULL);
    gCiaGuiWindow = hwnd;
    ShowWindow(hwnd, SW_SHOW);
    UpdateWindow(hwnd);

    while (GetMessage(&msg, NULL, 0, 0) > 0)
    {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
    return 0;
}

static void ciaStartGuiThread()
{
    if (gCiaGuiThread)
        return;
    gCiaGuiThread = CreateThread(NULL, 0, ciaGuiThreadProc, NULL, 0, &gCiaGuiThreadId);
}

static void ciaStopGuiThread()
{
    if (!gCiaGuiThread)
        return;
    if (gCiaGuiThreadId)
        PostThreadMessage(gCiaGuiThreadId, WM_QUIT, 0, 0);
    WaitForSingleObject(gCiaGuiThread, 2000);
    CloseHandle(gCiaGuiThread);
    gCiaGuiThread = NULL;
    gCiaGuiThreadId = 0;
}

static void ciaSendLuPdos(unsigned char index)
{
    CIA_LU_STATE lu;
    unsigned short status;
    unsigned char data[8];
    static const unsigned int pdo1[CIA_LU_COUNT] = {0x191, 0x1A1, 0x1B1, 0x1C1};
    static const unsigned int pdo2[CIA_LU_COUNT] = {0x192, 0x1A2, 0x1B2, 0x1C2};

    if (index >= CIA_LU_COUNT)
        return;

    EnterCriticalSection(&gCiaParamLock);
    lu = gCiaLu[index];
    LeaveCriticalSection(&gCiaParamLock);

    if (!lu.enabled)
        return;

    status = ciaLuStatusWord(lu);

    memset(data, 0, sizeof(data));
    ciaSetU16(data, 0, status);
    data[2] = 0xC0;
    ciaSendCanFrame(pdo1[index], data, 3);

    memset(data, 0, sizeof(data));
    ciaSetU16(data, 0, status);
    ciaSetU16(data, 2, lu.positionTenth);
    ciaSendCanFrame(pdo2[index], data, 4);
}

static void ciaSendHeartbeats()
{
    unsigned char data[1] = {0x05};
    unsigned char bcNode;
    unsigned char sdoNode;
    unsigned char bcHeartbeat;
    unsigned char sdoHeartbeat;

    EnterCriticalSection(&gCiaParamLock);
    bcNode = gCiaBcNode;
    sdoNode = gCiaSdoNode;
    bcHeartbeat = gCiaBcHeartbeatEnabled;
    sdoHeartbeat = gCiaSdoHeartbeatEnabled;
    LeaveCriticalSection(&gCiaParamLock);

    if (bcHeartbeat)
        ciaSendCanFrame(0x700 + bcNode, data, 1);
    if (sdoHeartbeat && sdoNode != bcNode)
        ciaSendCanFrame(0x700 + sdoNode, data, 1);
}

static unsigned char ciaSdoNodeForLu(unsigned char luIndex)
{
    unsigned char sdoNode;
    unsigned char singleNode;

    EnterCriticalSection(&gCiaParamLock);
    sdoNode = gCiaSdoNode;
    singleNode = gCiaSingleSdoNode;
    LeaveCriticalSection(&gCiaParamLock);

    if (singleNode)
        return sdoNode;
    return (unsigned char)(0x14 + luIndex);
}

static unsigned char ciaFindSdoValue(unsigned char requestNode, unsigned int object, unsigned char subIndex, unsigned long* value, unsigned char* bits)
{
    unsigned char luIndex;
    unsigned char expectedNode;

    if (object != 0x6104 && object != 0x6105)
        return 0;

    if (subIndex == 0)
    {
        expectedNode = ciaSdoNodeForLu(0);
        if (requestNode != expectedNode)
            return 0;
        *value = CIA_LU_COUNT;
        *bits = 8;
        return 1;
    }

    if (subIndex > CIA_LU_COUNT)
        return 0;

    luIndex = (unsigned char)(subIndex - 1);
    expectedNode = ciaSdoNodeForLu(luIndex);
    if (requestNode != expectedNode)
        return 0;

    EnterCriticalSection(&gCiaParamLock);
    if (object == 0x6104)
    {
        *value = gCiaLu[luIndex].shortCounter;
        *bits = 16;
    }
    else
    {
        *value = gCiaLu[luIndex].totalCounter;
        *bits = 32;
    }
    LeaveCriticalSection(&gCiaParamLock);
    return 1;
}

static void ciaSendSdoAbort(unsigned char node, unsigned int object, unsigned char subIndex)
{
    unsigned char data[8];

    memset(data, 0, sizeof(data));
    data[0] = 0x80;
    data[1] = (unsigned char)(object & 0xFF);
    data[2] = (unsigned char)((object >> 8) & 0xFF);
    data[3] = subIndex;
    data[4] = 0x00;
    data[5] = 0x00;
    data[6] = 0x02;
    data[7] = 0x06;
    ciaSendCanFrame(0x580 + node, data, 8);
}

static void ciaHandleSdoRequest(const STCAN_MSG& rx)
{
    unsigned int object;
    unsigned char node;
    unsigned char subIndex;
    unsigned long value = 0;
    unsigned char bits = 0;
    unsigned char data[8];

    if (rx.isExtended || rx.isRtr || rx.dlc < 8)
        return;
    if (rx.id < 0x601 || rx.id > 0x67F)
        return;
    if (rx.data[0] != 0x40)
        return;

    node = (unsigned char)(rx.id - 0x600);
    object = (unsigned int)rx.data[1] | ((unsigned int)rx.data[2] << 8);
    subIndex = rx.data[3];

    EnterCriticalSection(&gCiaParamLock);
    gCiaSdoRxCount++;
    gCiaLastSdoRequest = rx.id;
    LeaveCriticalSection(&gCiaParamLock);

    if (!ciaFindSdoValue(node, object, subIndex, &value, &bits))
    {
        ciaSendSdoAbort(node, object, subIndex);
        return;
    }

    memset(data, 0, sizeof(data));
    data[0] = (bits == 8) ? 0x4F : ((bits == 16) ? 0x4B : 0x43);
    data[1] = (unsigned char)(object & 0xFF);
    data[2] = (unsigned char)((object >> 8) & 0xFF);
    data[3] = subIndex;
    ciaSetU32(data, 4, value);
    ciaSendCanFrame(0x580 + node, data, 8);

    EnterCriticalSection(&gCiaParamLock);
    gCiaSdoTxCount++;
    gCiaLastSdoResponse = 0x580 + node;
    LeaveCriticalSection(&gCiaParamLock);
}

static void ciaUpdateWave()
{
    unsigned int tick = gCiaWaveTick++;
    static unsigned long lastUpdateMs = 0;
    static unsigned int lastCounterCycle = 0;
    unsigned long nowMs = GetTickCount();
    unsigned int counterCycle;

    if (lastUpdateMs && (nowMs - lastUpdateMs) < 80)
        return;
    lastUpdateMs = nowMs;

    EnterCriticalSection(&gCiaParamLock);
    if (gCiaWaveEnabled)
    {
        for (int i = 0; i < CIA_LU_COUNT; i++)
        {
            gCiaLu[i].ready = 1;
            gCiaLu[i].active = 1;
            gCiaLu[i].move = (unsigned char)ciaWaveValue(tick + i * 80, 480, 0, 5);
            gCiaLu[i].wu = (unsigned char)ciaWaveValue(tick + i * 70, 640, 0, 3);
            gCiaLu[i].cu = (unsigned char)ciaWaveValue(tick + i * 60, 600, 0, 3);
            gCiaLu[i].window = (unsigned char)ciaWaveValue(tick + i * 50, 720, 0, 2);
            gCiaLu[i].bin = (unsigned char)ciaWaveValue(tick + i * 40, 760, 0, 2);
            gCiaLu[i].positionTenth = (unsigned int)ciaWaveValue(tick + i * 90, 900, 0, 1000);
        }

        counterCycle = tick / 100;
        if (counterCycle != lastCounterCycle)
        {
            lastCounterCycle = counterCycle;
            for (int i = 0; i < CIA_LU_COUNT; i++)
            {
                gCiaLu[i].shortCounter = (gCiaLu[i].shortCounter + 1) & 0xFFFF;
                gCiaLu[i].totalCounter++;
            }
        }
    }
    LeaveCriticalSection(&gCiaParamLock);
}

/* Start BUSMASTER generated function - OnDLL_Load */
void OnDLL_Load()
{
    InitializeCriticalSection(&gMsgTxLock);
    InitializeCriticalSection(&gCiaParamLock);
    ciaStartGuiThread();
    Trace("CleANopenEmulator CAN DLL loaded");
}/* End BUSMASTER generated function - OnDLL_Load */

/* Start BUSMASTER generated function - OnDLL_Unload */
void OnDLL_Unload()
{
    Trace("CleANopenEmulator CAN DLL unloaded");
    ciaStopGuiThread();
    DeleteCriticalSection(&gCiaParamLock);
    DeleteCriticalSection(&gMsgTxLock);
}/* End BUSMASTER generated function - OnDLL_Unload */

/* Start BUSMASTER generated function - OnBus_Connect */
void OnBus_Connect()
{
    ciaSendHeartbeats();
}/* End BUSMASTER generated function - OnBus_Connect */

/* Start BUSMASTER generated function - OnTimer_CIA422_FAST_100 */
void OnTimer_CIA422_FAST_100()
{
    ciaUpdateWave();
    ciaSendLuPdos(0);
    ciaSendLuPdos(1);
    ciaSendLuPdos(2);
    ciaSendLuPdos(3);
}/* End BUSMASTER generated function - OnTimer_CIA422_FAST_100 */

/* Start BUSMASTER generated function - OnTimer_CIA422_HEARTBEAT_1000 */
void OnTimer_CIA422_HEARTBEAT_1000()
{
    ciaSendHeartbeats();
}/* End BUSMASTER generated function - OnTimer_CIA422_HEARTBEAT_1000 */

/* Start BUSMASTER generated function - OnMsg_All */
void OnMsg_All(STCAN_MSG RxMsg)
{
    ciaHandleSdoRequest(RxMsg);
}/* End BUSMASTER generated function - OnMsg_All */
