#define _CRT_SECURE_NO_WARNINGS

/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <stdlib.h>
#include <stdio.h>
#include "pcan_runtime.h"
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
#define DTC_ECU_COUNT 4
#define DTC_PER_ECU 4
#define DTC_ENTRY_COUNT (DTC_ECU_COUNT * DTC_PER_ECU)

struct DTC_ECU_CONFIG
{
    unsigned char enabled;
    unsigned char sourceAddress;
    unsigned char lampStatus;
    unsigned char lampFlash;
};

struct DTC_ENTRY
{
    unsigned long spn;
    unsigned char fmi;
    unsigned char occurrenceCount;
    unsigned char conversionMethod;
    unsigned char inDm1;
    unsigned char inDm2;
};

CRITICAL_SECTION gMsgTxLock;
CRITICAL_SECTION gDtcParamLock;
CRITICAL_SECTION gDtcTpLock;
HANDLE gDtcGuiThread = NULL;
DWORD gDtcGuiThreadId = 0;
HWND gDtcGuiWindow = NULL;
unsigned char gDtcCluster = 1;
unsigned char gDtcAutoDm1 = 1;
unsigned char gDtcGuiTopmost = 1;
volatile LONG gDtcSendDm1Pending = 0;
volatile LONG gDtcSendClaimPending = 0;
volatile LONG gDtcDm2RequestMask = 0;
unsigned char gDtcLastRequestSource = 0xFF;
unsigned char gDtcLastRequestDestination = 0xFF;
unsigned long gDtcDm1Cycles = 0;
unsigned long gDtcDm2Responses = 0;

DTC_ECU_CONFIG gDtcEcu[DTC_ECU_COUNT] =
{
    { 1, 0x00, 0x04, 0xFF },
    { 1, 0x03, 0x00, 0xFF },
    { 1, 0x0B, 0x00, 0xFF },
    { 1, 0x21, 0x00, 0xFF }
};

DTC_ENTRY gDtcEntry[DTC_ENTRY_COUNT] =
{
    { 110, 0, 1, 0, 1, 0 }, { 190, 2, 2, 0, 0, 0 },
    { 100, 4, 1, 0, 0, 1 }, { 0, 0, 0, 0, 0, 0 },
    { 177, 3, 1, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 },
    { 84, 9, 1, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 },
    { 520941, 3, 3, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 }
};
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_DTC_DM1_1000();
GCC_EXTERN void GCC_EXPORT OnTimer_DTC_SERVICE_100();
GCC_EXTERN void GCC_EXPORT OnMsg_All(STCAN_MSG RxMsg);
GCC_EXTERN void GCC_EXPORT OnDLL_Load();
GCC_EXTERN void GCC_EXPORT OnDLL_Unload();
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */

#define DTC_GUI_WM_SHUTDOWN (WM_APP + 20)
#define DTC_GUI_TIMER_STATUS 1
#define IDC_DTC_APPLY 2001
#define IDC_DTC_DEFAULT 2002
#define IDC_DTC_SEND_NOW 2003
#define IDC_DTC_CLEAR_DM2 2004
#define IDC_DTC_AUTO_DM1 2005
#define IDC_DTC_TOPMOST 2006
#define IDC_DTC_STATUS 2007
#define IDC_DTC_ECU_ENABLE_BASE 2100
#define IDC_DTC_ECU_SA_BASE 2120
#define IDC_DTC_ECU_LAMP_BASE 2140
#define IDC_DTC_ECU_FLASH_BASE 2160
#define IDC_DTC_DM1_BASE 2200
#define IDC_DTC_DM2_BASE 2240
#define IDC_DTC_SPN_BASE 2280
#define IDC_DTC_FMI_BASE 2320
#define IDC_DTC_OC_BASE 2360
#define IDC_DTC_CM_BASE 2400

static void dtcSendAllDm1();
static void dtcSendDm2ForMask(unsigned long mask);

static void dtcAtomicOr(volatile LONG* target, LONG mask)
{
    LONG previous;
    LONG combined;
    do
    {
        previous = *target;
        combined = previous | mask;
    }
    while (InterlockedCompareExchange(target, combined, previous) != previous);
}

static unsigned long dtcReadUnsigned(HWND hwnd, int id, unsigned long fallback, unsigned long maximum)
{
    char text[64];
    char* end = NULL;
    unsigned long value;
    GetDlgItemTextA(hwnd, id, text, sizeof(text));
    value = strtoul(text, &end, 0);
    if (end == text)
        return fallback;
    return value > maximum ? maximum : value;
}

static unsigned char dtcReadHexByte(HWND hwnd, int id, unsigned char fallback)
{
    char text[32];
    char* end = NULL;
    unsigned long value;
    GetDlgItemTextA(hwnd, id, text, sizeof(text));
    value = strtoul(text, &end, 16);
    return (end == text || value > 0xFF) ? fallback : (unsigned char)value;
}

static void dtcSetUnsigned(HWND hwnd, int id, unsigned long value)
{
    char text[32];
    sprintf(text, "%lu", value);
    SetDlgItemTextA(hwnd, id, text);
}

static void dtcSetHexByte(HWND hwnd, int id, unsigned char value)
{
    char text[8];
    sprintf(text, "%02X", value);
    SetDlgItemTextA(hwnd, id, text);
}

static HWND dtcCreateControl(HWND parent, const char* className, const char* text,
    DWORD style, int x, int y, int width, int height, int id)
{
    return CreateWindowExA(0, className, text, WS_CHILD | WS_VISIBLE | style,
        x, y, width, height, parent, (HMENU)(INT_PTR)id, GetModuleHandle(NULL), NULL);
}

static void dtcSetCheck(HWND hwnd, int id, unsigned char checked)
{
    CheckDlgButton(hwnd, id, checked ? BST_CHECKED : BST_UNCHECKED);
}

static unsigned char dtcGetCheck(HWND hwnd, int id)
{
    return IsDlgButtonChecked(hwnd, id) == BST_CHECKED ? 1 : 0;
}

static void dtcLoadGui(HWND hwnd, unsigned char defaults)
{
    static const unsigned char defaultSa[DTC_ECU_COUNT] = { 0x00, 0x03, 0x0B, 0x21 };
    static const unsigned long defaultSpn[DTC_ENTRY_COUNT] =
    {
        110, 190, 100, 0, 177, 0, 0, 0, 84, 0, 0, 0, 520941, 0, 0, 0
    };
    static const unsigned char defaultFmi[DTC_ENTRY_COUNT] =
    {
        0, 2, 4, 0, 3, 0, 0, 0, 9, 0, 0, 0, 3, 0, 0, 0
    };
    int i;

    EnterCriticalSection(&gDtcParamLock);
    if (!defaults)
        dtcSetCheck(hwnd, IDC_DTC_AUTO_DM1, gDtcAutoDm1);
    dtcSetCheck(hwnd, IDC_DTC_TOPMOST, gDtcGuiTopmost);
    for (i = 0; i < DTC_ECU_COUNT; i++)
    {
        dtcSetCheck(hwnd, IDC_DTC_ECU_ENABLE_BASE + i, defaults ? 1 : gDtcEcu[i].enabled);
        dtcSetHexByte(hwnd, IDC_DTC_ECU_SA_BASE + i, defaults ? defaultSa[i] : gDtcEcu[i].sourceAddress);
        dtcSetHexByte(hwnd, IDC_DTC_ECU_LAMP_BASE + i, defaults ? (i == 0 ? 0x04 : 0) : gDtcEcu[i].lampStatus);
        dtcSetHexByte(hwnd, IDC_DTC_ECU_FLASH_BASE + i, defaults ? 0xFF : gDtcEcu[i].lampFlash);
    }
    for (i = 0; i < DTC_ENTRY_COUNT; i++)
    {
        dtcSetCheck(hwnd, IDC_DTC_DM1_BASE + i, defaults ? (i == 0) : gDtcEntry[i].inDm1);
        dtcSetCheck(hwnd, IDC_DTC_DM2_BASE + i, defaults ? (i == 2) : gDtcEntry[i].inDm2);
        dtcSetUnsigned(hwnd, IDC_DTC_SPN_BASE + i, defaults ? defaultSpn[i] : gDtcEntry[i].spn);
        dtcSetUnsigned(hwnd, IDC_DTC_FMI_BASE + i, defaults ? defaultFmi[i] : gDtcEntry[i].fmi);
        dtcSetUnsigned(hwnd, IDC_DTC_OC_BASE + i, defaults ? (defaultSpn[i] ? 1 : 0) : gDtcEntry[i].occurrenceCount);
        dtcSetCheck(hwnd, IDC_DTC_CM_BASE + i, defaults ? 0 : gDtcEntry[i].conversionMethod);
    }
    LeaveCriticalSection(&gDtcParamLock);
}

static void dtcApplyGui(HWND hwnd)
{
    int i;
    EnterCriticalSection(&gDtcParamLock);
    gDtcAutoDm1 = dtcGetCheck(hwnd, IDC_DTC_AUTO_DM1);
    for (i = 0; i < DTC_ECU_COUNT; i++)
    {
        gDtcEcu[i].enabled = dtcGetCheck(hwnd, IDC_DTC_ECU_ENABLE_BASE + i);
        gDtcEcu[i].sourceAddress = dtcReadHexByte(hwnd, IDC_DTC_ECU_SA_BASE + i, gDtcEcu[i].sourceAddress);
        gDtcEcu[i].lampStatus = dtcReadHexByte(hwnd, IDC_DTC_ECU_LAMP_BASE + i, gDtcEcu[i].lampStatus);
        gDtcEcu[i].lampFlash = dtcReadHexByte(hwnd, IDC_DTC_ECU_FLASH_BASE + i, gDtcEcu[i].lampFlash);
    }
    for (i = 0; i < DTC_ENTRY_COUNT; i++)
    {
        gDtcEntry[i].inDm1 = dtcGetCheck(hwnd, IDC_DTC_DM1_BASE + i);
        gDtcEntry[i].inDm2 = dtcGetCheck(hwnd, IDC_DTC_DM2_BASE + i);
        gDtcEntry[i].spn = dtcReadUnsigned(hwnd, IDC_DTC_SPN_BASE + i, gDtcEntry[i].spn, 0x7FFFF);
        gDtcEntry[i].fmi = (unsigned char)dtcReadUnsigned(hwnd, IDC_DTC_FMI_BASE + i, gDtcEntry[i].fmi, 31);
        gDtcEntry[i].occurrenceCount = (unsigned char)dtcReadUnsigned(hwnd, IDC_DTC_OC_BASE + i, gDtcEntry[i].occurrenceCount, 127);
        gDtcEntry[i].conversionMethod = dtcGetCheck(hwnd, IDC_DTC_CM_BASE + i);
    }
    LeaveCriticalSection(&gDtcParamLock);
    InterlockedExchange(&gDtcSendClaimPending, 1);
    InterlockedExchange(&gDtcSendDm1Pending, 1);
}

static void dtcUpdateStatus(HWND hwnd)
{
    char text[256];
    unsigned char source;
    unsigned char destination;
    unsigned long dm1Cycles;
    unsigned long dm2Responses;
    EnterCriticalSection(&gDtcParamLock);
    source = gDtcLastRequestSource;
    destination = gDtcLastRequestDestination;
    dm1Cycles = gDtcDm1Cycles;
    dm2Responses = gDtcDm2Responses;
    LeaveCriticalSection(&gDtcParamLock);
    if (source == 0xFF)
        sprintf(text, "DM1: %lu   DM2 responses: %lu   Last request: none", dm1Cycles, dm2Responses);
    else
        sprintf(text, "DM1: %lu   DM2 responses: %lu   Request: SA %02X -> DA %02X", dm1Cycles, dm2Responses, source, destination);
    SetDlgItemTextA(hwnd, IDC_DTC_STATUS, text);
}

static void dtcCreateGuiControls(HWND hwnd)
{
    int i;
    int y;
    char text[160];
    dtcCreateControl(hwnd, "BUTTON", "Apply", BS_PUSHBUTTON, 18, 12, 80, 28, IDC_DTC_APPLY);
    dtcCreateControl(hwnd, "BUTTON", "Default", BS_PUSHBUTTON, 108, 12, 80, 28, IDC_DTC_DEFAULT);
    dtcCreateControl(hwnd, "BUTTON", "Send DM1 now", BS_PUSHBUTTON, 198, 12, 105, 28, IDC_DTC_SEND_NOW);
    dtcCreateControl(hwnd, "BUTTON", "Clear DM2", BS_PUSHBUTTON, 313, 12, 90, 28, IDC_DTC_CLEAR_DM2);
    dtcCreateControl(hwnd, "BUTTON", "Auto DM1 (1 s)", BS_AUTOCHECKBOX, 420, 15, 125, 22, IDC_DTC_AUTO_DM1);
    dtcCreateControl(hwnd, "BUTTON", "Always on top", BS_AUTOCHECKBOX, 565, 15, 130, 22, IDC_DTC_TOPMOST);

    dtcCreateControl(hwnd, "BUTTON", "ECU configuration", BS_GROUPBOX, 12, 48, 930, 150, 0);
    dtcCreateControl(hwnd, "STATIC", "ECU", SS_LEFT, 32, 72, 40, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "Enabled", SS_LEFT, 82, 72, 60, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "SA hex", SS_LEFT, 175, 72, 60, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "Lamp status", SS_LEFT, 275, 72, 90, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "Lamp flash", SS_LEFT, 410, 72, 90, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "MIL[7:6] RSL[5:4] AWL[3:2] PL[1:0]", SS_LEFT, 535, 72, 330, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "0=off/slow, 1=on/fast, 3=N/A/no flash", SS_LEFT, 535, 96, 330, 20, 0);
    for (i = 0; i < DTC_ECU_COUNT; i++)
    {
        y = 96 + i * 24;
        sprintf(text, "%d", i + 1);
        dtcCreateControl(hwnd, "STATIC", text, SS_LEFT, 42, y + 3, 30, 20, 0);
        dtcCreateControl(hwnd, "BUTTON", "", BS_AUTOCHECKBOX, 96, y, 24, 22, IDC_DTC_ECU_ENABLE_BASE + i);
        dtcCreateControl(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 175, y, 58, 22, IDC_DTC_ECU_SA_BASE + i);
        dtcCreateControl(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 275, y, 72, 22, IDC_DTC_ECU_LAMP_BASE + i);
        dtcCreateControl(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 410, y, 72, 22, IDC_DTC_ECU_FLASH_BASE + i);
    }

    dtcCreateControl(hwnd, "BUTTON", "Diagnostic Trouble Codes", BS_GROUPBOX, 12, 208, 930, 372, 0);
    dtcCreateControl(hwnd, "STATIC", "ECU", SS_CENTER, 32, 230, 42, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "Slot", SS_CENTER, 78, 230, 42, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "DM1", SS_CENTER, 130, 230, 46, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "DM2", SS_CENTER, 180, 230, 46, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "SPN", SS_LEFT, 238, 230, 130, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "FMI", SS_CENTER, 375, 230, 52, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "OC", SS_CENTER, 437, 230, 52, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "CM", SS_CENTER, 500, 230, 52, 20, 0);
    dtcCreateControl(hwnd, "STATIC", "DM2 after Request PGN 59904 for FECB", SS_LEFT, 570, 230, 340, 20, 0);
    for (i = 0; i < DTC_ENTRY_COUNT; i++)
    {
        y = 254 + i * 19;
        sprintf(text, "%d", i / DTC_PER_ECU + 1);
        dtcCreateControl(hwnd, "STATIC", text, SS_CENTER, 32, y + 2, 42, 19, 0);
        sprintf(text, "%d", i % DTC_PER_ECU + 1);
        dtcCreateControl(hwnd, "STATIC", text, SS_CENTER, 78, y + 2, 42, 19, 0);
        dtcCreateControl(hwnd, "BUTTON", "", BS_AUTOCHECKBOX, 145, y, 24, 20, IDC_DTC_DM1_BASE + i);
        dtcCreateControl(hwnd, "BUTTON", "", BS_AUTOCHECKBOX, 195, y, 24, 20, IDC_DTC_DM2_BASE + i);
        dtcCreateControl(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 238, y, 125, 20, IDC_DTC_SPN_BASE + i);
        dtcCreateControl(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 375, y, 52, 20, IDC_DTC_FMI_BASE + i);
        dtcCreateControl(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 437, y, 52, 20, IDC_DTC_OC_BASE + i);
        dtcCreateControl(hwnd, "BUTTON", "", BS_AUTOCHECKBOX, 515, y, 24, 20, IDC_DTC_CM_BASE + i);
        if (i % DTC_PER_ECU == 0)
        {
            sprintf(text, "DM1 18FECAxx / DM2 18FECBxx, ECU %d", i / DTC_PER_ECU + 1);
            dtcCreateControl(hwnd, "STATIC", text, SS_LEFT, 570, y + 2, 340, 19, 0);
        }
        if (i == DTC_ENTRY_COUNT - 1)
            dtcCreateControl(hwnd, "STATIC", "2+ DTCs from one ECU use TP.BAM/TP.DT.", SS_LEFT, 570, y + 2, 340, 19, 0);
    }
    dtcCreateControl(hwnd, "STATIC", "", SS_LEFT, 24, 586, 900, 22, IDC_DTC_STATUS);
}

static LRESULT CALLBACK dtcGuiWindowProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
{
    int i;
    switch (message)
    {
    case WM_CREATE:
        dtcCreateGuiControls(hwnd);
        PcanRuntimeCreateControls(hwnd, 12, 610, 930);
        dtcLoadGui(hwnd, 0);
        SetTimer(hwnd, DTC_GUI_TIMER_STATUS, 500, NULL);
        SetWindowPos(hwnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
        return 0;
    case WM_COMMAND:
        if (PcanRuntimeHandleCommand(hwnd, LOWORD(wParam), HIWORD(wParam)))
            return 0;
        switch (LOWORD(wParam))
        {
        case IDC_DTC_APPLY:
            dtcApplyGui(hwnd);
            return 0;
        case IDC_DTC_DEFAULT:
            dtcLoadGui(hwnd, 1);
            return 0;
        case IDC_DTC_SEND_NOW:
            dtcApplyGui(hwnd);
            return 0;
        case IDC_DTC_CLEAR_DM2:
            for (i = 0; i < DTC_ENTRY_COUNT; i++)
                dtcSetCheck(hwnd, IDC_DTC_DM2_BASE + i, 0);
            dtcApplyGui(hwnd);
            return 0;
        case IDC_DTC_TOPMOST:
            EnterCriticalSection(&gDtcParamLock);
            gDtcGuiTopmost = dtcGetCheck(hwnd, IDC_DTC_TOPMOST);
            LeaveCriticalSection(&gDtcParamLock);
            SetWindowPos(hwnd, dtcGetCheck(hwnd, IDC_DTC_TOPMOST) ? HWND_TOPMOST : HWND_NOTOPMOST,
                0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
            return 0;
        }
        break;
    case WM_TIMER:
        dtcUpdateStatus(hwnd);
        PcanRuntimeRefreshStatus(hwnd);
        return 0;
    case WM_CLOSE:
        DestroyWindow(hwnd);
        return 0;
    case DTC_GUI_WM_SHUTDOWN:
        DestroyWindow(hwnd);
        return 0;
    case WM_DESTROY:
        KillTimer(hwnd, DTC_GUI_TIMER_STATUS);
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProc(hwnd, message, wParam, lParam);
}

static DWORD WINAPI dtcGuiThreadProc(LPVOID parameter)
{
    WNDCLASSA windowClass;
    MSG message;
    HINSTANCE instance = GetModuleHandle(NULL);
    (void)parameter;
    ZeroMemory(&windowClass, sizeof(windowClass));
    windowClass.lpfnWndProc = dtcGuiWindowProc;
    windowClass.hInstance = instance;
    windowClass.hCursor = LoadCursor(NULL, IDC_ARROW);
    windowClass.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
    windowClass.lpszClassName = "BUSMASTER_J1939_DTC_EMULATOR";
    RegisterClassA(&windowClass);
    gDtcGuiWindow = CreateWindowExA(WS_EX_TOPMOST, windowClass.lpszClassName, "PCAN J1939 DTC Emulator",
        WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX,
        0, 0, 970, 740, NULL, NULL, instance, NULL);
    if (gDtcGuiWindow)
    {
        ShowWindow(gDtcGuiWindow, SW_SHOW);
        UpdateWindow(gDtcGuiWindow);
        while (GetMessage(&message, NULL, 0, 0) > 0)
        {
            TranslateMessage(&message);
            DispatchMessage(&message);
        }
    }
    gDtcGuiWindow = NULL;
    return 0;
}

static void dtcStartGuiThread()
{
    if (!gDtcGuiThread)
        gDtcGuiThread = CreateThread(NULL, 0, dtcGuiThreadProc, NULL, 0, &gDtcGuiThreadId);
}

static void dtcStopGuiThread()
{
    if (gDtcGuiWindow)
        PostMessage(gDtcGuiWindow, DTC_GUI_WM_SHUTDOWN, 0, 0);
    if (gDtcGuiThread)
    {
        WaitForSingleObject(gDtcGuiThread, 2000);
        CloseHandle(gDtcGuiThread);
        gDtcGuiThread = NULL;
    }
}

static unsigned int dtcMakeJ1939Id(unsigned char priority, unsigned int pgnOrPfPs, unsigned char sourceAddress)
{
    return (((unsigned int)(priority & 7)) << 26) | ((pgnOrPfPs & 0x3FFFF) << 8) | sourceAddress;
}

static void dtcSendCanFrame(unsigned int canId, const unsigned char* data, unsigned char dlc)
{
    STCAN_MSG msg(canId, true, dlc, false);
    unsigned int i;
    EnterCriticalSection(&gDtcParamLock);
    msg.cluster = gDtcCluster;
    LeaveCriticalSection(&gDtcParamLock);
    msg.isExtended = true;
    msg.isRtr = false;
    msg.isCanfd = false;
    msg.dlc = dlc;
    for (i = 0; i < dlc && i < 8; i++)
        msg.data[i] = data[i];
    EnterCriticalSection(&gMsgTxLock);
    SendMsg(msg);
    LeaveCriticalSection(&gMsgTxLock);
}

static void dtcSendPayload(unsigned int pgn, const unsigned char* data, unsigned int length, unsigned char sourceAddress)
{
    unsigned char cm[8];
    unsigned char dt[8];
    unsigned int packetCount;
    unsigned int packet;
    unsigned int offset;
    unsigned int i;

    EnterCriticalSection(&gDtcTpLock);
    if (length <= 8)
    {
        dtcSendCanFrame(dtcMakeJ1939Id(6, pgn, sourceAddress), data, (unsigned char)length);
        LeaveCriticalSection(&gDtcTpLock);
        return;
    }

    packetCount = (length + 6) / 7;
    cm[0] = 0x20;
    cm[1] = (unsigned char)(length & 0xFF);
    cm[2] = (unsigned char)((length >> 8) & 0xFF);
    cm[3] = (unsigned char)packetCount;
    cm[4] = 0xFF;
    cm[5] = (unsigned char)(pgn & 0xFF);
    cm[6] = (unsigned char)((pgn >> 8) & 0xFF);
    cm[7] = (unsigned char)((pgn >> 16) & 0xFF);
    dtcSendCanFrame(dtcMakeJ1939Id(6, 0x00ECFF, sourceAddress), cm, 8);
    Sleep(60);

    for (packet = 1; packet <= packetCount; packet++)
    {
        dt[0] = (unsigned char)packet;
        offset = (packet - 1) * 7;
        for (i = 0; i < 7; i++)
            dt[i + 1] = offset + i < length ? data[offset + i] : 0xFF;
        dtcSendCanFrame(dtcMakeJ1939Id(6, 0x00EBFF, sourceAddress), dt, 8);
        Sleep(60);
    }
    LeaveCriticalSection(&gDtcTpLock);
}

static void dtcPackEntry(unsigned char* output, const DTC_ENTRY& entry)
{
    unsigned long spn = entry.spn & 0x7FFFF;
    output[0] = (unsigned char)(spn & 0xFF);
    output[1] = (unsigned char)((spn >> 8) & 0xFF);
    output[2] = (unsigned char)((((spn >> 16) & 7) << 5) | (entry.fmi & 0x1F));
    output[3] = (unsigned char)((entry.conversionMethod ? 0x80 : 0) | (entry.occurrenceCount & 0x7F));
}

static void dtcSendDiagnosticMessage(int ecuIndex, unsigned int pgn, unsigned char useDm2)
{
    DTC_ECU_CONFIG ecu;
    DTC_ENTRY entries[DTC_PER_ECU];
    unsigned char payload[2 + DTC_PER_ECU * 4];
    unsigned int count = 0;
    unsigned int i;

    EnterCriticalSection(&gDtcParamLock);
    ecu = gDtcEcu[ecuIndex];
    for (i = 0; i < DTC_PER_ECU; i++)
        entries[i] = gDtcEntry[ecuIndex * DTC_PER_ECU + i];
    LeaveCriticalSection(&gDtcParamLock);
    if (!ecu.enabled)
        return;

    payload[0] = ecu.lampStatus;
    payload[1] = ecu.lampFlash;
    for (i = 0; i < DTC_PER_ECU; i++)
    {
        if ((useDm2 && entries[i].inDm2) || (!useDm2 && entries[i].inDm1))
        {
            dtcPackEntry(&payload[2 + count * 4], entries[i]);
            count++;
        }
    }

    if (count == 0)
    {
        payload[2] = payload[3] = payload[4] = payload[5] = 0;
        payload[6] = payload[7] = 0xFF;
        dtcSendPayload(pgn, payload, 8, ecu.sourceAddress);
    }
    else if (count == 1)
    {
        payload[6] = payload[7] = 0xFF;
        dtcSendPayload(pgn, payload, 8, ecu.sourceAddress);
    }
    else
    {
        dtcSendPayload(pgn, payload, 2 + count * 4, ecu.sourceAddress);
    }
}

static void dtcSendAllDm1()
{
    int i;
    for (i = 0; i < DTC_ECU_COUNT; i++)
        dtcSendDiagnosticMessage(i, 0x00FECA, 0);
    EnterCriticalSection(&gDtcParamLock);
    gDtcDm1Cycles++;
    LeaveCriticalSection(&gDtcParamLock);
}

static void dtcSendDm2ForMask(unsigned long mask)
{
    int i;
    for (i = 0; i < DTC_ECU_COUNT; i++)
    {
        if (mask & (1UL << i))
        {
            dtcSendDiagnosticMessage(i, 0x00FECB, 1);
            EnterCriticalSection(&gDtcParamLock);
            gDtcDm2Responses++;
            LeaveCriticalSection(&gDtcParamLock);
        }
    }
}

static void dtcSendAddressClaims()
{
    DTC_ECU_CONFIG ecu[DTC_ECU_COUNT];
    unsigned char name[8];
    int i;
    int j;
    EnterCriticalSection(&gDtcParamLock);
    for (i = 0; i < DTC_ECU_COUNT; i++)
        ecu[i] = gDtcEcu[i];
    LeaveCriticalSection(&gDtcParamLock);
    for (i = 0; i < DTC_ECU_COUNT; i++)
    {
        if (!ecu[i].enabled)
            continue;
        for (j = 0; j < 8; j++)
            name[j] = 0;
        name[0] = (unsigned char)(i + 1);
        name[1] = ecu[i].sourceAddress;
        name[7] = 0x80;
        dtcSendCanFrame(dtcMakeJ1939Id(6, 0x00EEFF, ecu[i].sourceAddress), name, 8);
    }
}

static void dtcHandleRequest(const STCAN_MSG& rx)
{
    unsigned int id;
    unsigned char destination;
    unsigned char source;
    unsigned long requestedPgn;
    unsigned long mask = 0;
    int i;

    if (!rx.isExtended || rx.isRtr || rx.dlc < 3)
        return;
    id = rx.id;
    if (((id >> 16) & 0xFF) != 0xEA)
        return;
    requestedPgn = (unsigned long)rx.data[0] |
        ((unsigned long)rx.data[1] << 8) |
        ((unsigned long)rx.data[2] << 16);
    if (requestedPgn != 0x00FECB)
        return;

    destination = (unsigned char)((id >> 8) & 0xFF);
    source = (unsigned char)(id & 0xFF);
    EnterCriticalSection(&gDtcParamLock);
    gDtcLastRequestSource = source;
    gDtcLastRequestDestination = destination;
    for (i = 0; i < DTC_ECU_COUNT; i++)
    {
        if (gDtcEcu[i].enabled && (destination == 0xFF || destination == gDtcEcu[i].sourceAddress))
            mask |= 1UL << i;
    }
    LeaveCriticalSection(&gDtcParamLock);
    if (mask)
        dtcAtomicOr(&gDtcDm2RequestMask, (LONG)mask);
}

/* Start BUSMASTER generated function - OnDLL_Load */
void OnDLL_Load()
{
    InitializeCriticalSection(&gMsgTxLock);
    InitializeCriticalSection(&gDtcParamLock);
    InitializeCriticalSection(&gDtcTpLock);
    dtcStartGuiThread();
    Trace("J1939DtcEmulator CAN DLL loaded");
}/* End BUSMASTER generated function - OnDLL_Load */

/* Start BUSMASTER generated function - OnDLL_Unload */
void OnDLL_Unload()
{
    Trace("J1939DtcEmulator CAN DLL unloaded");
    dtcStopGuiThread();
    DeleteCriticalSection(&gDtcTpLock);
    DeleteCriticalSection(&gDtcParamLock);
    DeleteCriticalSection(&gMsgTxLock);
}/* End BUSMASTER generated function - OnDLL_Unload */

/* Start BUSMASTER generated function - OnBus_Connect */
void OnBus_Connect()
{
    InterlockedExchange(&gDtcSendClaimPending, 1);
    InterlockedExchange(&gDtcSendDm1Pending, 1);
}/* End BUSMASTER generated function - OnBus_Connect */

/* Start BUSMASTER generated function - OnTimer_DTC_DM1_1000 */
void OnTimer_DTC_DM1_1000()
{
    unsigned char enabled;
    EnterCriticalSection(&gDtcParamLock);
    enabled = gDtcAutoDm1;
    LeaveCriticalSection(&gDtcParamLock);
    if (enabled)
        dtcSendAllDm1();
}/* End BUSMASTER generated function - OnTimer_DTC_DM1_1000 */

/* Start BUSMASTER generated function - OnTimer_DTC_SERVICE_100 */
void OnTimer_DTC_SERVICE_100()
{
    unsigned long requestMask;
    if (InterlockedExchange(&gDtcSendClaimPending, 0))
        dtcSendAddressClaims();
    if (InterlockedExchange(&gDtcSendDm1Pending, 0))
        dtcSendAllDm1();
    requestMask = (unsigned long)InterlockedExchange(&gDtcDm2RequestMask, 0);
    if (requestMask)
        dtcSendDm2ForMask(requestMask);
}/* End BUSMASTER generated function - OnTimer_DTC_SERVICE_100 */

/* Start BUSMASTER generated function - OnMsg_All */
void OnMsg_All(STCAN_MSG RxMsg)
{
    dtcHandleRequest(RxMsg);
}/* End BUSMASTER generated function - OnMsg_All */
