#define _CRT_SECURE_NO_WARNINGS

/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <stdlib.h>
#include <stdio.h>
#include "pcan_runtime.h"
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
CRITICAL_SECTION gMsgTxLock;
CRITICAL_SECTION gFmsParamLock;
HANDLE gFmsGuiThread = NULL;
DWORD gFmsGuiThreadId = 0;
HWND gFmsGuiWindow = NULL;
unsigned int gFmsWaveTick = 0;
unsigned int gFmsClockTick = 0;
unsigned char gFmsGuiTopmost = 1;
unsigned char gFmsWaveEnabled = 1;
unsigned char gFmsEngineRunning = 1;

unsigned char gFmsCluster = 1;
unsigned char gFmsSourceAddress = 0x02;

double gFmsEngineSpeedRpm = 1500.0;
int gFmsActualEnginePercentTorque = 40;
int gFmsEnginePercentLoad = 35;
int gFmsAcceleratorPedalPosition = 20;

double gFmsWheelBasedSpeedKph = 50.0;
double gFmsTachographSpeedKph = 50.0;
unsigned char gFmsBrakeSwitch = 0;
unsigned char gFmsClutchSwitch = 0;
unsigned char gFmsCruiseControlActive = 0;
unsigned char gFmsPtoState = 31;
unsigned char gFmsParkingBrakeSwitch = 0;

double gFmsTotalFuelUsedL = 12345.0;
double gFmsHighResolutionFuelUsedL = 12345.0;
double gFmsFuelRateLph = 12.5;
double gFmsInstantFuelEconomyKmL = 3.0;
unsigned char gFmsFuelLevel1Percent = 75;
unsigned char gFmsDieselExhaustFluidLevelPercent = 70;

double gFmsEngineHours = 1234.0;
double gFmsTotalVehicleDistanceKm = 123456.0;
double gFmsServiceDistanceKm = 25000.0;
double gFmsGrossCombinationVehicleWeightKg = 18000.0;
unsigned char gFmsAtLeastOnePtoEngaged = 0;

int gFmsCoolantTemperatureC = 85;
double gFmsAmbientAirTemperatureC = 20.0;
double gFmsEngineOilTemperatureC = 90.0;
double gFmsBrakePedalPositionPercent = 0.0;
unsigned int gFmsServiceBrakeAirPressure1Kpa = 800;
unsigned int gFmsServiceBrakeAirPressure2Kpa = 800;

unsigned char gFmsVehicleMotion = 1;
unsigned char gFmsVehicleOverspeed = 0;
unsigned char gFmsDriver1Card = 1;
unsigned char gFmsDriver2Card = 0;

unsigned char gFmsBusVersionMajor = 3;
unsigned char gFmsBusVersionMinor = 0;
unsigned char gFmsTruckVersionMajor = 3;
unsigned char gFmsTruckVersionMinor = 0;

unsigned int gFmsYear = 2026;
unsigned char gFmsMonth = 9;
unsigned char gFmsDay = 9;
unsigned char gFmsHour = 12;
unsigned char gFmsMinute = 0;
unsigned char gFmsSecond = 0;

unsigned char gFmsFrontDoorOpen = 0;
unsigned char gFmsMiddleDoorOpen = 0;
unsigned char gFmsRearDoorOpen = 0;
double gFmsAlternatorSpeedRpm = 3000.0;
unsigned char gFmsTellTaleBlockId = 0;
unsigned char gFmsTellTaleStatus[4][15] =
{
    { 3, 7, 7, 7, 7, 7, 1, 2, 7, 0, 2, 3, 1, 7, 7 },
    { 7, 7, 0, 7, 2, 0, 3, 3, 7, 0, 0, 2, 2, 3, 3 },
    { 2, 0, 7, 0, 0, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7 },
    { 7, 3, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0 }
};

unsigned char gFmsTpmsEnabled = 1;
unsigned char gFmsTpmsSniffFramesEnabled = 1;
unsigned char gFmsTpmsSourceAddress = 0xC8;
unsigned int gFmsTirePressureKpa[6] = { 900, 890, 900, 890, 900, 890 };
double gFmsTireTemperatureC[6] = { 15.125, 15.125, 15.125, 15.125, 15.125, 15.125 };
unsigned char gFmsTireLocation[6] = { 0x17, 0x19, 0x27, 0x29, 0x37, 0x39 };
unsigned char gFmsTpmsFe5eIndex[6] = { 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B };
unsigned char gFmsTpmsFe5eMarker[6] = { 0x30, 0x30, 0x30, 0x30, 0x31, 0x32 };
unsigned char gFmsTpmsFec6Status[6] = { 0x7D, 0x7D, 0x7D, 0x7D, 0x7D, 0x7D };

char gFmsVin[18] = "FMSDEMO0000000001";
char gFmsDriver1Id[20] = "PL 15312080961";
char gFmsDriver2Id[20] = "";
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_FMS_EEC1_20();
GCC_EXTERN void GCC_EXPORT OnTimer_FMS_EEC2_50();
GCC_EXTERN void GCC_EXPORT OnTimer_FMS_100();
GCC_EXTERN void GCC_EXPORT OnTimer_FMS_1000();
GCC_EXTERN void GCC_EXPORT OnTimer_FMS_DI_10000();
GCC_EXTERN void GCC_EXPORT OnTimer_FMS_WAVE_100();
GCC_EXTERN void GCC_EXPORT OnDLL_Load();
GCC_EXTERN void GCC_EXPORT OnDLL_Unload();
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */

static unsigned char fmsClampU8(int value, int minValue, int maxValue);

#define FMS_GUI_WM_SHUTDOWN (WM_APP + 10)
#define FMS_GUI_TIMER_REFRESH 1
#define IDC_APPLY 1001
#define IDC_DEFAULT 1002
#define IDC_STATUS 1003
#define IDC_AUTO_WAVE 1004
#define IDC_ENGINE_RUNNING 1005
#define IDC_BRAKE 1006
#define IDC_CLUTCH 1007
#define IDC_CRUISE 1008
#define IDC_PTO 1009
#define IDC_PARKING 1010
#define IDC_MOTION 1011
#define IDC_OVERSPEED 1012
#define IDC_DRIVER1_CARD 1013
#define IDC_DRIVER2_CARD 1014
#define IDC_FRONT_DOOR 1015
#define IDC_MIDDLE_DOOR 1016
#define IDC_REAR_DOOR 1017
#define IDC_TPMS_ENABLED 1018
#define IDC_TPMS_SNIFF 1019
#define IDC_TOPMOST 1020
#define IDC_SA 1100
#define IDC_TPMS_SA 1101
#define IDC_RPM 1102
#define IDC_TORQUE 1103
#define IDC_LOAD 1104
#define IDC_ACCEL 1105
#define IDC_SPEED 1106
#define IDC_TACHO_SPEED 1107
#define IDC_FUEL_USED 1108
#define IDC_FUEL_RATE 1109
#define IDC_FUEL_ECONOMY 1110
#define IDC_FUEL_LEVEL 1111
#define IDC_DEF_LEVEL 1112
#define IDC_ENGINE_HOURS 1113
#define IDC_DISTANCE 1114
#define IDC_SERVICE_DISTANCE 1115
#define IDC_WEIGHT 1116
#define IDC_COOLANT 1117
#define IDC_AMBIENT 1118
#define IDC_AIR1 1119
#define IDC_AIR2 1120
#define IDC_ALTERNATOR 1121
#define IDC_TT_BLOCK 1122
#define IDC_YEAR 1123
#define IDC_MONTH 1124
#define IDC_DAY 1125
#define IDC_HOUR 1126
#define IDC_MINUTE 1127
#define IDC_SECOND 1128
#define IDC_BUS_VER_MAJOR 1129
#define IDC_BUS_VER_MINOR 1130
#define IDC_TRUCK_VER_MAJOR 1131
#define IDC_TRUCK_VER_MINOR 1132
#define IDC_VIN 1133
#define IDC_DRIVER1_ID 1134
#define IDC_DRIVER2_ID 1135
#define IDC_OIL_TEMP 1136
#define IDC_BRAKE_PEDAL 1137
#define IDC_TIRE_LOCATION_BASE 1200
#define IDC_TIRE_PRESSURE_BASE 1210
#define IDC_TIRE_TEMP_BASE 1220
#define IDC_TT_STATUS_BASE 1240

static HWND fmsGuiGetItem(HWND hwnd, int controlId)
{
    return GetDlgItem(hwnd, controlId);
}

static void fmsGuiSetCheck(HWND hwnd, int controlId, unsigned char checked)
{
    SendMessage(fmsGuiGetItem(hwnd, controlId), BM_SETCHECK, checked ? BST_CHECKED : BST_UNCHECKED, 0);
}

static void fmsGuiSetText(HWND hwnd, int controlId, const char* value)
{
    HWND control = fmsGuiGetItem(hwnd, controlId);

    if (GetFocus() != control)
        SetWindowText(control, value);
}

static void fmsGuiSetInt(HWND hwnd, int controlId, int value)
{
    char text[32];
    sprintf(text, "%d", value);
    fmsGuiSetText(hwnd, controlId, text);
}

static void fmsGuiSetUInt(HWND hwnd, int controlId, unsigned int value)
{
    char text[32];
    sprintf(text, "%u", value);
    fmsGuiSetText(hwnd, controlId, text);
}

static void fmsGuiSetHexByte(HWND hwnd, int controlId, unsigned char value)
{
    char text[8];
    sprintf(text, "%02X", (unsigned int)value);
    fmsGuiSetText(hwnd, controlId, text);
}

static void fmsGuiSetDouble(HWND hwnd, int controlId, double value, int decimals)
{
    char text[48];

    if (decimals == 0)
        sprintf(text, "%.0f", value);
    else if (decimals == 1)
        sprintf(text, "%.1f", value);
    else if (decimals == 2)
        sprintf(text, "%.2f", value);
    else
        sprintf(text, "%.3f", value);

    fmsGuiSetText(hwnd, controlId, text);
}

static int fmsGuiReadInt(HWND hwnd, int controlId, int minValue, int maxValue)
{
    char text[64];
    int value;

    GetWindowText(fmsGuiGetItem(hwnd, controlId), text, sizeof(text));
    value = atoi(text);
    if (value < minValue)
        value = minValue;
    if (value > maxValue)
        value = maxValue;
    return value;
}

static unsigned int fmsGuiReadUInt(HWND hwnd, int controlId, unsigned int minValue, unsigned int maxValue)
{
    char text[64];
    unsigned long value;

    GetWindowText(fmsGuiGetItem(hwnd, controlId), text, sizeof(text));
    value = strtoul(text, NULL, 10);
    if (value < minValue)
        value = minValue;
    if (value > maxValue)
        value = maxValue;
    return (unsigned int)value;
}

static unsigned char fmsGuiReadHexByte(HWND hwnd, int controlId)
{
    char text[64];
    unsigned long value;

    GetWindowText(fmsGuiGetItem(hwnd, controlId), text, sizeof(text));
    value = strtoul(text, NULL, 16);
    if (value > 255)
        value = 255;
    return (unsigned char)value;
}

static double fmsGuiReadDouble(HWND hwnd, int controlId, double minValue, double maxValue)
{
    char text[64];
    double value;

    GetWindowText(fmsGuiGetItem(hwnd, controlId), text, sizeof(text));
    value = atof(text);
    if (value < minValue)
        value = minValue;
    if (value > maxValue)
        value = maxValue;
    return value;
}

static unsigned char fmsGuiReadCheck(HWND hwnd, int controlId)
{
    return (SendMessage(fmsGuiGetItem(hwnd, controlId), BM_GETCHECK, 0, 0) == BST_CHECKED) ? 1 : 0;
}

static void fmsGuiUpdateStatus(HWND hwnd)
{
    char text[128];
    unsigned char sourceAddress;
    unsigned char tpmsSourceAddress;

    EnterCriticalSection(&gFmsParamLock);
    sourceAddress = gFmsSourceAddress;
    tpmsSourceAddress = gFmsTpmsSourceAddress;
    LeaveCriticalSection(&gFmsParamLock);

    sprintf(text, "FMS SA: %02X    TPMS SA: %02X    Address claim sent on connect", (unsigned int)sourceAddress, (unsigned int)tpmsSourceAddress);
    SetWindowText(fmsGuiGetItem(hwnd, IDC_STATUS), text);
}

static void fmsGuiRefresh(HWND hwnd)
{
    char text[80];
    unsigned char tireLocation[6];
    unsigned int tirePressure[6];
    double tireTemperature[6];
    unsigned char tellTaleStatus[4][15];
    int i;
    int j;

    EnterCriticalSection(&gFmsParamLock);
    fmsGuiSetCheck(hwnd, IDC_TOPMOST, gFmsGuiTopmost);
    fmsGuiSetCheck(hwnd, IDC_AUTO_WAVE, gFmsWaveEnabled);
    fmsGuiSetCheck(hwnd, IDC_ENGINE_RUNNING, gFmsEngineRunning);
    fmsGuiSetCheck(hwnd, IDC_BRAKE, gFmsBrakeSwitch);
    fmsGuiSetCheck(hwnd, IDC_CLUTCH, gFmsClutchSwitch);
    fmsGuiSetCheck(hwnd, IDC_CRUISE, gFmsCruiseControlActive);
    fmsGuiSetCheck(hwnd, IDC_PTO, gFmsAtLeastOnePtoEngaged);
    fmsGuiSetCheck(hwnd, IDC_PARKING, gFmsParkingBrakeSwitch);
    fmsGuiSetCheck(hwnd, IDC_MOTION, gFmsVehicleMotion);
    fmsGuiSetCheck(hwnd, IDC_OVERSPEED, gFmsVehicleOverspeed);
    fmsGuiSetCheck(hwnd, IDC_DRIVER1_CARD, gFmsDriver1Card);
    fmsGuiSetCheck(hwnd, IDC_DRIVER2_CARD, gFmsDriver2Card);
    fmsGuiSetCheck(hwnd, IDC_FRONT_DOOR, gFmsFrontDoorOpen);
    fmsGuiSetCheck(hwnd, IDC_MIDDLE_DOOR, gFmsMiddleDoorOpen);
    fmsGuiSetCheck(hwnd, IDC_REAR_DOOR, gFmsRearDoorOpen);
    fmsGuiSetCheck(hwnd, IDC_TPMS_ENABLED, gFmsTpmsEnabled);
    fmsGuiSetCheck(hwnd, IDC_TPMS_SNIFF, gFmsTpmsSniffFramesEnabled);

    fmsGuiSetHexByte(hwnd, IDC_SA, gFmsSourceAddress);
    fmsGuiSetHexByte(hwnd, IDC_TPMS_SA, gFmsTpmsSourceAddress);
    fmsGuiSetDouble(hwnd, IDC_RPM, gFmsEngineSpeedRpm, 0);
    fmsGuiSetInt(hwnd, IDC_TORQUE, gFmsActualEnginePercentTorque);
    fmsGuiSetInt(hwnd, IDC_LOAD, gFmsEnginePercentLoad);
    fmsGuiSetInt(hwnd, IDC_ACCEL, gFmsAcceleratorPedalPosition);
    fmsGuiSetDouble(hwnd, IDC_SPEED, gFmsWheelBasedSpeedKph, 1);
    fmsGuiSetDouble(hwnd, IDC_TACHO_SPEED, gFmsTachographSpeedKph, 1);
    fmsGuiSetDouble(hwnd, IDC_FUEL_USED, gFmsTotalFuelUsedL, 1);
    fmsGuiSetDouble(hwnd, IDC_FUEL_RATE, gFmsFuelRateLph, 1);
    fmsGuiSetDouble(hwnd, IDC_FUEL_ECONOMY, gFmsInstantFuelEconomyKmL, 2);
    fmsGuiSetUInt(hwnd, IDC_FUEL_LEVEL, gFmsFuelLevel1Percent);
    fmsGuiSetUInt(hwnd, IDC_DEF_LEVEL, gFmsDieselExhaustFluidLevelPercent);
    fmsGuiSetDouble(hwnd, IDC_ENGINE_HOURS, gFmsEngineHours, 1);
    fmsGuiSetDouble(hwnd, IDC_DISTANCE, gFmsTotalVehicleDistanceKm, 1);
    fmsGuiSetDouble(hwnd, IDC_SERVICE_DISTANCE, gFmsServiceDistanceKm, 1);
    fmsGuiSetDouble(hwnd, IDC_WEIGHT, gFmsGrossCombinationVehicleWeightKg, 0);
    fmsGuiSetInt(hwnd, IDC_COOLANT, gFmsCoolantTemperatureC);
    fmsGuiSetDouble(hwnd, IDC_OIL_TEMP, gFmsEngineOilTemperatureC, 1);
    fmsGuiSetDouble(hwnd, IDC_AMBIENT, gFmsAmbientAirTemperatureC, 1);
    fmsGuiSetDouble(hwnd, IDC_BRAKE_PEDAL, gFmsBrakePedalPositionPercent, 1);
    fmsGuiSetUInt(hwnd, IDC_AIR1, gFmsServiceBrakeAirPressure1Kpa);
    fmsGuiSetUInt(hwnd, IDC_AIR2, gFmsServiceBrakeAirPressure2Kpa);
    fmsGuiSetDouble(hwnd, IDC_ALTERNATOR, gFmsAlternatorSpeedRpm, 0);
    fmsGuiSetUInt(hwnd, IDC_TT_BLOCK, gFmsTellTaleBlockId);
    fmsGuiSetUInt(hwnd, IDC_YEAR, gFmsYear);
    fmsGuiSetUInt(hwnd, IDC_MONTH, gFmsMonth);
    fmsGuiSetUInt(hwnd, IDC_DAY, gFmsDay);
    fmsGuiSetUInt(hwnd, IDC_HOUR, gFmsHour);
    fmsGuiSetUInt(hwnd, IDC_MINUTE, gFmsMinute);
    fmsGuiSetUInt(hwnd, IDC_SECOND, gFmsSecond);
    fmsGuiSetUInt(hwnd, IDC_BUS_VER_MAJOR, gFmsBusVersionMajor);
    fmsGuiSetUInt(hwnd, IDC_BUS_VER_MINOR, gFmsBusVersionMinor);
    fmsGuiSetUInt(hwnd, IDC_TRUCK_VER_MAJOR, gFmsTruckVersionMajor);
    fmsGuiSetUInt(hwnd, IDC_TRUCK_VER_MINOR, gFmsTruckVersionMinor);
    fmsGuiSetText(hwnd, IDC_VIN, gFmsVin);
    fmsGuiSetText(hwnd, IDC_DRIVER1_ID, gFmsDriver1Id);
    fmsGuiSetText(hwnd, IDC_DRIVER2_ID, gFmsDriver2Id);
    for (i = 0; i < 6; i++)
    {
        tireLocation[i] = gFmsTireLocation[i];
        tirePressure[i] = gFmsTirePressureKpa[i];
        tireTemperature[i] = gFmsTireTemperatureC[i];
    }
    for (i = 0; i < 4; i++)
        for (j = 0; j < 15; j++)
            tellTaleStatus[i][j] = gFmsTellTaleStatus[i][j];
    LeaveCriticalSection(&gFmsParamLock);

    for (i = 0; i < 6; i++)
    {
        fmsGuiSetHexByte(hwnd, IDC_TIRE_LOCATION_BASE + i, tireLocation[i]);
        fmsGuiSetUInt(hwnd, IDC_TIRE_PRESSURE_BASE + i, tirePressure[i]);
        fmsGuiSetDouble(hwnd, IDC_TIRE_TEMP_BASE + i, tireTemperature[i], 3);
    }

    for (i = 0; i < 4; i++)
    {
        for (j = 0; j < 15; j++)
            text[j] = (char)('0' + (tellTaleStatus[i][j] & 0x07));
        text[15] = 0;
        fmsGuiSetText(hwnd, IDC_TT_STATUS_BASE + i, text);
    }

    fmsGuiUpdateStatus(hwnd);
}

static HWND fmsGuiCreateChild(HWND hwnd, const char* className, const char* text, DWORD style, int x, int y, int w, int h, int controlId)
{
    return CreateWindowExA(0, className, text, WS_CHILD | WS_VISIBLE | style, x, y, w, h, hwnd, (HMENU)(INT_PTR)controlId, GetModuleHandle(NULL), NULL);
}

static void fmsGuiCreateLabel(HWND hwnd, const char* text, int x, int y, int w)
{
    fmsGuiCreateChild(hwnd, "STATIC", text, 0, x, y + 3, w, 20, 0);
}

static void fmsGuiCreateEditRow(HWND hwnd, const char* label, int controlId, int x, int y, int labelW, int editW)
{
    fmsGuiCreateLabel(hwnd, label, x, y, labelW);
    fmsGuiCreateChild(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, x + labelW, y, editW, 22, controlId);
}

static void fmsGuiCreateGroup(HWND hwnd, const char* label, int x, int y, int w, int h)
{
    fmsGuiCreateChild(hwnd, "BUTTON", label, BS_GROUPBOX, x, y, w, h, 0);
}

static void fmsGuiCreateControls(HWND hwnd)
{
    int i;
    char text[32];

    fmsGuiCreateChild(hwnd, "BUTTON", "Apply", 0, 18, 12, 80, 28, IDC_APPLY);
    fmsGuiCreateChild(hwnd, "BUTTON", "Default", 0, 108, 12, 80, 28, IDC_DEFAULT);
    fmsGuiCreateChild(hwnd, "BUTTON", "Auto wave", BS_AUTOCHECKBOX, 205, 15, 120, 24, IDC_AUTO_WAVE);
    fmsGuiCreateChild(hwnd, "STATIC", "", 0, 345, 18, 360, 22, IDC_STATUS);
    fmsGuiCreateChild(hwnd, "BUTTON", "Always on top", BS_AUTOCHECKBOX, 930, 15, 150, 22, IDC_TOPMOST);

    fmsGuiCreateGroup(hwnd, "Engine / Vehicle", 12, 48, 350, 232);
    fmsGuiCreateEditRow(hwnd, "FMS SA hex", IDC_SA, 28, 74, 110, 70);
    fmsGuiCreateEditRow(hwnd, "RPM", IDC_RPM, 28, 102, 110, 70);
    fmsGuiCreateEditRow(hwnd, "Torque %", IDC_TORQUE, 28, 130, 110, 70);
    fmsGuiCreateEditRow(hwnd, "Load %", IDC_LOAD, 28, 158, 110, 70);
    fmsGuiCreateEditRow(hwnd, "Accelerator %", IDC_ACCEL, 28, 186, 110, 70);
    fmsGuiCreateEditRow(hwnd, "Speed km/h", IDC_SPEED, 28, 214, 110, 70);
    fmsGuiCreateEditRow(hwnd, "Tacho km/h", IDC_TACHO_SPEED, 28, 242, 110, 70);
    fmsGuiCreateChild(hwnd, "BUTTON", "Engine running", BS_AUTOCHECKBOX, 220, 74, 130, 22, IDC_ENGINE_RUNNING);
    fmsGuiCreateChild(hwnd, "BUTTON", "Vehicle motion", BS_AUTOCHECKBOX, 220, 102, 130, 22, IDC_MOTION);
    fmsGuiCreateChild(hwnd, "BUTTON", "Overspeed", BS_AUTOCHECKBOX, 220, 130, 130, 22, IDC_OVERSPEED);
    fmsGuiCreateChild(hwnd, "BUTTON", "Cruise", BS_AUTOCHECKBOX, 220, 158, 130, 22, IDC_CRUISE);

    fmsGuiCreateGroup(hwnd, "Switches / Doors", 375, 48, 340, 188);
    fmsGuiCreateChild(hwnd, "BUTTON", "Brake", BS_AUTOCHECKBOX, 392, 76, 100, 22, IDC_BRAKE);
    fmsGuiCreateChild(hwnd, "BUTTON", "Clutch", BS_AUTOCHECKBOX, 392, 104, 100, 22, IDC_CLUTCH);
    fmsGuiCreateChild(hwnd, "BUTTON", "Parking brake", BS_AUTOCHECKBOX, 392, 132, 130, 22, IDC_PARKING);
    fmsGuiCreateChild(hwnd, "BUTTON", "PTO", BS_AUTOCHECKBOX, 392, 160, 100, 22, IDC_PTO);
    fmsGuiCreateChild(hwnd, "BUTTON", "Driver 1 card", BS_AUTOCHECKBOX, 545, 76, 140, 22, IDC_DRIVER1_CARD);
    fmsGuiCreateChild(hwnd, "BUTTON", "Driver 2 card", BS_AUTOCHECKBOX, 545, 104, 140, 22, IDC_DRIVER2_CARD);
    fmsGuiCreateChild(hwnd, "BUTTON", "Front door", BS_AUTOCHECKBOX, 545, 132, 140, 22, IDC_FRONT_DOOR);
    fmsGuiCreateChild(hwnd, "BUTTON", "Middle door", BS_AUTOCHECKBOX, 545, 160, 140, 22, IDC_MIDDLE_DOOR);
    fmsGuiCreateChild(hwnd, "BUTTON", "Rear door", BS_AUTOCHECKBOX, 545, 188, 140, 22, IDC_REAR_DOOR);

    fmsGuiCreateGroup(hwnd, "Fuel / Counters", 12, 290, 350, 260);
    fmsGuiCreateEditRow(hwnd, "Fuel used L", IDC_FUEL_USED, 28, 316, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Fuel rate L/h", IDC_FUEL_RATE, 28, 344, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Fuel economy", IDC_FUEL_ECONOMY, 28, 372, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Fuel level %", IDC_FUEL_LEVEL, 28, 400, 130, 80);
    fmsGuiCreateEditRow(hwnd, "DEF level %", IDC_DEF_LEVEL, 28, 428, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Engine hours", IDC_ENGINE_HOURS, 28, 456, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Distance km", IDC_DISTANCE, 28, 484, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Service km", IDC_SERVICE_DISTANCE, 28, 512, 130, 80);

    fmsGuiCreateGroup(hwnd, "Environment / Vehicle Data", 375, 246, 340, 288);
    fmsGuiCreateEditRow(hwnd, "Weight kg", IDC_WEIGHT, 392, 272, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Coolant C", IDC_COOLANT, 392, 300, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Oil temp C", IDC_OIL_TEMP, 392, 328, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Ambient C", IDC_AMBIENT, 392, 356, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Air 1 kPa", IDC_AIR1, 392, 384, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Air 2 kPa", IDC_AIR2, 392, 412, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Brake pedal %", IDC_BRAKE_PEDAL, 392, 440, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Alternator rpm", IDC_ALTERNATOR, 392, 468, 130, 80);
    fmsGuiCreateEditRow(hwnd, "Tell tale block", IDC_TT_BLOCK, 392, 496, 130, 80);

    fmsGuiCreateGroup(hwnd, "Date / Version", 375, 542, 340, 126);
    fmsGuiCreateEditRow(hwnd, "Year", IDC_YEAR, 391, 568, 55, 40);
    fmsGuiCreateEditRow(hwnd, "Month", IDC_MONTH, 517, 568, 50, 35);
    fmsGuiCreateEditRow(hwnd, "Day", IDC_DAY, 637, 568, 35, 34);
    fmsGuiCreateEditRow(hwnd, "Hour", IDC_HOUR, 391, 596, 55, 40);
    fmsGuiCreateEditRow(hwnd, "Minute", IDC_MINUTE, 517, 596, 50, 35);
    fmsGuiCreateEditRow(hwnd, "Second", IDC_SECOND, 627, 596, 55, 25);
    fmsGuiCreateEditRow(hwnd, "Bus ver", IDC_BUS_VER_MAJOR, 391, 634, 55, 35);
    fmsGuiCreateEditRow(hwnd, ".", IDC_BUS_VER_MINOR, 487, 634, 12, 25);
    fmsGuiCreateEditRow(hwnd, "Truck ver", IDC_TRUCK_VER_MAJOR, 561, 634, 65, 35);
    fmsGuiCreateEditRow(hwnd, ".", IDC_TRUCK_VER_MINOR, 667, 634, 12, 25);

    fmsGuiCreateGroup(hwnd, "TPMS", 738, 48, 360, 288);
    fmsGuiCreateEditRow(hwnd, "TPMS SA hex", IDC_TPMS_SA, 755, 74, 100, 55);
    fmsGuiCreateChild(hwnd, "BUTTON", "TPMS enabled", BS_AUTOCHECKBOX, 938, 74, 130, 22, IDC_TPMS_ENABLED);
    fmsGuiCreateChild(hwnd, "BUTTON", "18FE5E/18FEC6", BS_AUTOCHECKBOX, 938, 102, 145, 22, IDC_TPMS_SNIFF);
    fmsGuiCreateLabel(hwnd, "ID", 823, 140, 42);
    fmsGuiCreateLabel(hwnd, "kPa", 891, 140, 58);
    fmsGuiCreateLabel(hwnd, "C", 984, 140, 58);
    for (i = 0; i < 6; i++)
    {
        sprintf(text, "Tire %d", i + 1);
        fmsGuiCreateLabel(hwnd, text, 755, 166 + i * 28, 58);
        fmsGuiCreateChild(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 823, 163 + i * 28, 52, 22, IDC_TIRE_LOCATION_BASE + i);
        fmsGuiCreateChild(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 891, 163 + i * 28, 76, 22, IDC_TIRE_PRESSURE_BASE + i);
        fmsGuiCreateChild(hwnd, "EDIT", "", WS_BORDER | ES_AUTOHSCROLL, 984, 163 + i * 28, 90, 22, IDC_TIRE_TEMP_BASE + i);
    }

    fmsGuiCreateGroup(hwnd, "Text data", 12, 560, 350, 112);
    fmsGuiCreateEditRow(hwnd, "VIN", IDC_VIN, 28, 586, 70, 230);
    fmsGuiCreateEditRow(hwnd, "Driver 1", IDC_DRIVER1_ID, 28, 614, 70, 230);
    fmsGuiCreateEditRow(hwnd, "Driver 2", IDC_DRIVER2_ID, 28, 642, 70, 230);

    fmsGuiCreateGroup(hwnd, "Tell tales status", 738, 352, 360, 148);
    fmsGuiCreateEditRow(hwnd, "Block 0", IDC_TT_STATUS_BASE + 0, 755, 380, 78, 230);
    fmsGuiCreateEditRow(hwnd, "Block 1", IDC_TT_STATUS_BASE + 1, 755, 408, 78, 230);
    fmsGuiCreateEditRow(hwnd, "Block 2", IDC_TT_STATUS_BASE + 2, 755, 436, 78, 230);
    fmsGuiCreateEditRow(hwnd, "Block 3", IDC_TT_STATUS_BASE + 3, 755, 464, 78, 230);

    fmsGuiRefresh(hwnd);
}

static void fmsGuiReadTellTales(HWND hwnd, int controlId, unsigned char* status)
{
    char text[64];
    int i;
    int out = 0;

    GetWindowText(fmsGuiGetItem(hwnd, controlId), text, sizeof(text));
    for (i = 0; text[i] != 0 && out < 15; i++)
    {
        if (text[i] >= '0' && text[i] <= '7')
        {
            status[out] = (unsigned char)(text[i] - '0');
            out++;
        }
    }
}

static int fmsGuiIsCheckControl(int controlId)
{
    return controlId == IDC_AUTO_WAVE ||
           controlId == IDC_ENGINE_RUNNING ||
           controlId == IDC_BRAKE ||
           controlId == IDC_CLUTCH ||
           controlId == IDC_CRUISE ||
           controlId == IDC_PTO ||
           controlId == IDC_PARKING ||
           controlId == IDC_MOTION ||
           controlId == IDC_OVERSPEED ||
           controlId == IDC_DRIVER1_CARD ||
           controlId == IDC_DRIVER2_CARD ||
           controlId == IDC_FRONT_DOOR ||
           controlId == IDC_MIDDLE_DOOR ||
           controlId == IDC_REAR_DOOR ||
           controlId == IDC_TPMS_ENABLED ||
           controlId == IDC_TPMS_SNIFF ||
           controlId == IDC_TOPMOST;
}

static void fmsGuiApplyTopmost(HWND hwnd)
{
    unsigned char topmost;

    EnterCriticalSection(&gFmsParamLock);
    topmost = gFmsGuiTopmost;
    LeaveCriticalSection(&gFmsParamLock);

    SetWindowPos(hwnd, topmost ? HWND_TOPMOST : HWND_NOTOPMOST, 0, 0, 0, 0,
        SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
}

static void fmsGuiApplyChecks(HWND hwnd)
{
    EnterCriticalSection(&gFmsParamLock);
    gFmsGuiTopmost = fmsGuiReadCheck(hwnd, IDC_TOPMOST);
    gFmsWaveEnabled = fmsGuiReadCheck(hwnd, IDC_AUTO_WAVE);
    gFmsEngineRunning = fmsGuiReadCheck(hwnd, IDC_ENGINE_RUNNING);
    gFmsBrakeSwitch = fmsGuiReadCheck(hwnd, IDC_BRAKE);
    gFmsClutchSwitch = fmsGuiReadCheck(hwnd, IDC_CLUTCH);
    gFmsCruiseControlActive = fmsGuiReadCheck(hwnd, IDC_CRUISE);
    gFmsAtLeastOnePtoEngaged = fmsGuiReadCheck(hwnd, IDC_PTO);
    gFmsPtoState = gFmsAtLeastOnePtoEngaged ? 5 : 31;
    gFmsParkingBrakeSwitch = fmsGuiReadCheck(hwnd, IDC_PARKING);
    gFmsVehicleMotion = fmsGuiReadCheck(hwnd, IDC_MOTION);
    gFmsVehicleOverspeed = fmsGuiReadCheck(hwnd, IDC_OVERSPEED);
    gFmsDriver1Card = fmsGuiReadCheck(hwnd, IDC_DRIVER1_CARD);
    gFmsDriver2Card = fmsGuiReadCheck(hwnd, IDC_DRIVER2_CARD);
    gFmsFrontDoorOpen = fmsGuiReadCheck(hwnd, IDC_FRONT_DOOR);
    gFmsMiddleDoorOpen = fmsGuiReadCheck(hwnd, IDC_MIDDLE_DOOR);
    gFmsRearDoorOpen = fmsGuiReadCheck(hwnd, IDC_REAR_DOOR);
    gFmsTpmsEnabled = fmsGuiReadCheck(hwnd, IDC_TPMS_ENABLED);
    gFmsTpmsSniffFramesEnabled = fmsGuiReadCheck(hwnd, IDC_TPMS_SNIFF);

    if (!gFmsEngineRunning)
    {
        gFmsEngineSpeedRpm = 0.0;
        gFmsActualEnginePercentTorque = 0;
        gFmsEnginePercentLoad = 0;
        gFmsAcceleratorPedalPosition = 0;
    }

    LeaveCriticalSection(&gFmsParamLock);
    fmsGuiApplyTopmost(hwnd);
}

static void fmsLoadDefaultValues()
{
    static const unsigned char defaultTellTaleStatus[4][15] =
    {
        { 3, 7, 7, 7, 7, 7, 1, 2, 7, 0, 2, 3, 1, 7, 7 },
        { 7, 7, 0, 7, 2, 0, 3, 3, 7, 0, 0, 2, 2, 3, 3 },
        { 2, 0, 7, 0, 0, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7 },
        { 7, 3, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0 }
    };
    static const unsigned int defaultTirePressureKpa[6] = { 900, 890, 900, 890, 900, 890 };
    static const double defaultTireTemperatureC[6] = { 15.125, 15.125, 15.125, 15.125, 15.125, 15.125 };
    static const unsigned char defaultTireLocation[6] = { 0x17, 0x19, 0x27, 0x29, 0x37, 0x39 };
    int i;
    int j;

    EnterCriticalSection(&gFmsParamLock);
    gFmsWaveTick = 0;
    gFmsClockTick = 0;
    gFmsGuiTopmost = 1;
    gFmsEngineRunning = 1;
    gFmsSourceAddress = 0x02;

    gFmsEngineSpeedRpm = 1500.0;
    gFmsActualEnginePercentTorque = 40;
    gFmsEnginePercentLoad = 35;
    gFmsAcceleratorPedalPosition = 20;
    gFmsWheelBasedSpeedKph = 50.0;
    gFmsTachographSpeedKph = 50.0;
    gFmsBrakeSwitch = 0;
    gFmsClutchSwitch = 0;
    gFmsCruiseControlActive = 0;
    gFmsPtoState = 31;
    gFmsParkingBrakeSwitch = 0;

    gFmsTotalFuelUsedL = 12345.0;
    gFmsHighResolutionFuelUsedL = 12345.0;
    gFmsFuelRateLph = 12.5;
    gFmsInstantFuelEconomyKmL = 3.0;
    gFmsFuelLevel1Percent = 75;
    gFmsDieselExhaustFluidLevelPercent = 70;
    gFmsEngineHours = 1234.0;
    gFmsTotalVehicleDistanceKm = 123456.0;
    gFmsServiceDistanceKm = 25000.0;
    gFmsGrossCombinationVehicleWeightKg = 18000.0;
    gFmsAtLeastOnePtoEngaged = 0;

    gFmsCoolantTemperatureC = 85;
    gFmsAmbientAirTemperatureC = 20.0;
    gFmsEngineOilTemperatureC = 90.0;
    gFmsBrakePedalPositionPercent = 0.0;
    gFmsServiceBrakeAirPressure1Kpa = 800;
    gFmsServiceBrakeAirPressure2Kpa = 800;
    gFmsVehicleMotion = 1;
    gFmsVehicleOverspeed = 0;
    gFmsDriver1Card = 1;
    gFmsDriver2Card = 0;

    gFmsBusVersionMajor = 3;
    gFmsBusVersionMinor = 0;
    gFmsTruckVersionMajor = 3;
    gFmsTruckVersionMinor = 0;
    gFmsYear = 2026;
    gFmsMonth = 9;
    gFmsDay = 9;
    gFmsHour = 12;
    gFmsMinute = 0;
    gFmsSecond = 0;

    gFmsFrontDoorOpen = 0;
    gFmsMiddleDoorOpen = 0;
    gFmsRearDoorOpen = 0;
    gFmsAlternatorSpeedRpm = 3000.0;
    gFmsTellTaleBlockId = 0;
    for (i = 0; i < 4; i++)
        for (j = 0; j < 15; j++)
            gFmsTellTaleStatus[i][j] = defaultTellTaleStatus[i][j];

    gFmsTpmsEnabled = 1;
    gFmsTpmsSniffFramesEnabled = 1;
    gFmsTpmsSourceAddress = 0xC8;
    for (i = 0; i < 6; i++)
    {
        gFmsTirePressureKpa[i] = defaultTirePressureKpa[i];
        gFmsTireTemperatureC[i] = defaultTireTemperatureC[i];
        gFmsTireLocation[i] = defaultTireLocation[i];
    }

    lstrcpynA(gFmsVin, "FMSDEMO0000000001", sizeof(gFmsVin));
    lstrcpynA(gFmsDriver1Id, "PL 15312080961", sizeof(gFmsDriver1Id));
    lstrcpynA(gFmsDriver2Id, "", sizeof(gFmsDriver2Id));
    LeaveCriticalSection(&gFmsParamLock);
}

static void fmsGuiLoadDefaults(HWND hwnd)
{
    fmsLoadDefaultValues();
    fmsGuiApplyTopmost(hwnd);
    fmsGuiRefresh(hwnd);
}

static void fmsGuiApply(HWND hwnd)
{
    char text[80];
    int i;

    EnterCriticalSection(&gFmsParamLock);
    gFmsGuiTopmost = fmsGuiReadCheck(hwnd, IDC_TOPMOST);
    gFmsWaveEnabled = fmsGuiReadCheck(hwnd, IDC_AUTO_WAVE);
    gFmsEngineRunning = fmsGuiReadCheck(hwnd, IDC_ENGINE_RUNNING);
    gFmsBrakeSwitch = fmsGuiReadCheck(hwnd, IDC_BRAKE);
    gFmsClutchSwitch = fmsGuiReadCheck(hwnd, IDC_CLUTCH);
    gFmsCruiseControlActive = fmsGuiReadCheck(hwnd, IDC_CRUISE);
    gFmsAtLeastOnePtoEngaged = fmsGuiReadCheck(hwnd, IDC_PTO);
    gFmsPtoState = gFmsAtLeastOnePtoEngaged ? 5 : 31;
    gFmsParkingBrakeSwitch = fmsGuiReadCheck(hwnd, IDC_PARKING);
    gFmsVehicleMotion = fmsGuiReadCheck(hwnd, IDC_MOTION);
    gFmsVehicleOverspeed = fmsGuiReadCheck(hwnd, IDC_OVERSPEED);
    gFmsDriver1Card = fmsGuiReadCheck(hwnd, IDC_DRIVER1_CARD);
    gFmsDriver2Card = fmsGuiReadCheck(hwnd, IDC_DRIVER2_CARD);
    gFmsFrontDoorOpen = fmsGuiReadCheck(hwnd, IDC_FRONT_DOOR);
    gFmsMiddleDoorOpen = fmsGuiReadCheck(hwnd, IDC_MIDDLE_DOOR);
    gFmsRearDoorOpen = fmsGuiReadCheck(hwnd, IDC_REAR_DOOR);
    gFmsTpmsEnabled = fmsGuiReadCheck(hwnd, IDC_TPMS_ENABLED);
    gFmsTpmsSniffFramesEnabled = fmsGuiReadCheck(hwnd, IDC_TPMS_SNIFF);

    gFmsSourceAddress = fmsGuiReadHexByte(hwnd, IDC_SA);
    gFmsTpmsSourceAddress = fmsGuiReadHexByte(hwnd, IDC_TPMS_SA);
    gFmsEngineSpeedRpm = fmsGuiReadDouble(hwnd, IDC_RPM, 0.0, 2500.0);
    gFmsActualEnginePercentTorque = fmsGuiReadInt(hwnd, IDC_TORQUE, -125, 125);
    gFmsEnginePercentLoad = fmsGuiReadInt(hwnd, IDC_LOAD, 0, 125);
    gFmsAcceleratorPedalPosition = fmsGuiReadInt(hwnd, IDC_ACCEL, 0, 100);
    gFmsWheelBasedSpeedKph = fmsGuiReadDouble(hwnd, IDC_SPEED, 0.0, 250.0);
    gFmsTachographSpeedKph = fmsGuiReadDouble(hwnd, IDC_TACHO_SPEED, 0.0, 250.0);
    gFmsTotalFuelUsedL = fmsGuiReadDouble(hwnd, IDC_FUEL_USED, 0.0, 2105540600.0);
    gFmsHighResolutionFuelUsedL = gFmsTotalFuelUsedL;
    gFmsFuelRateLph = fmsGuiReadDouble(hwnd, IDC_FUEL_RATE, 0.0, 3212.75);
    gFmsInstantFuelEconomyKmL = fmsGuiReadDouble(hwnd, IDC_FUEL_ECONOMY, 0.0, 125.5);
    gFmsFuelLevel1Percent = fmsClampU8(fmsGuiReadInt(hwnd, IDC_FUEL_LEVEL, 0, 100), 0, 100);
    gFmsDieselExhaustFluidLevelPercent = fmsClampU8(fmsGuiReadInt(hwnd, IDC_DEF_LEVEL, 0, 100), 0, 100);
    gFmsEngineHours = fmsGuiReadDouble(hwnd, IDC_ENGINE_HOURS, 0.0, 210554060.0);
    gFmsTotalVehicleDistanceKm = fmsGuiReadDouble(hwnd, IDC_DISTANCE, 0.0, 21055406.0);
    gFmsServiceDistanceKm = fmsGuiReadDouble(hwnd, IDC_SERVICE_DISTANCE, -32768.0, 32767.0);
    gFmsGrossCombinationVehicleWeightKg = fmsGuiReadDouble(hwnd, IDC_WEIGHT, 0.0, 642550.0);
    gFmsCoolantTemperatureC = fmsGuiReadInt(hwnd, IDC_COOLANT, -40, 210);
    gFmsEngineOilTemperatureC = fmsGuiReadDouble(hwnd, IDC_OIL_TEMP, -273.0, 1735.0);
    gFmsAmbientAirTemperatureC = fmsGuiReadDouble(hwnd, IDC_AMBIENT, -273.0, 1735.0);
    gFmsBrakePedalPositionPercent = fmsGuiReadDouble(hwnd, IDC_BRAKE_PEDAL, 0.0, 100.0);
    gFmsServiceBrakeAirPressure1Kpa = fmsGuiReadUInt(hwnd, IDC_AIR1, 0, 2000);
    gFmsServiceBrakeAirPressure2Kpa = fmsGuiReadUInt(hwnd, IDC_AIR2, 0, 2000);
    gFmsAlternatorSpeedRpm = fmsGuiReadDouble(hwnd, IDC_ALTERNATOR, 0.0, 8000.0);
    gFmsTellTaleBlockId = fmsClampU8(fmsGuiReadInt(hwnd, IDC_TT_BLOCK, 0, 3), 0, 3);
    gFmsYear = fmsGuiReadUInt(hwnd, IDC_YEAR, 1985, 2235);
    gFmsMonth = fmsClampU8(fmsGuiReadInt(hwnd, IDC_MONTH, 1, 12), 1, 12);
    gFmsDay = fmsClampU8(fmsGuiReadInt(hwnd, IDC_DAY, 1, 31), 1, 31);
    gFmsHour = fmsClampU8(fmsGuiReadInt(hwnd, IDC_HOUR, 0, 23), 0, 23);
    gFmsMinute = fmsClampU8(fmsGuiReadInt(hwnd, IDC_MINUTE, 0, 59), 0, 59);
    gFmsSecond = fmsClampU8(fmsGuiReadInt(hwnd, IDC_SECOND, 0, 59), 0, 59);
    gFmsBusVersionMajor = fmsClampU8(fmsGuiReadInt(hwnd, IDC_BUS_VER_MAJOR, 0, 9), 0, 9);
    gFmsBusVersionMinor = fmsClampU8(fmsGuiReadInt(hwnd, IDC_BUS_VER_MINOR, 0, 9), 0, 9);
    gFmsTruckVersionMajor = fmsClampU8(fmsGuiReadInt(hwnd, IDC_TRUCK_VER_MAJOR, 0, 9), 0, 9);
    gFmsTruckVersionMinor = fmsClampU8(fmsGuiReadInt(hwnd, IDC_TRUCK_VER_MINOR, 0, 9), 0, 9);

    GetWindowText(fmsGuiGetItem(hwnd, IDC_VIN), gFmsVin, sizeof(gFmsVin));
    gFmsVin[sizeof(gFmsVin) - 1] = 0;
    GetWindowText(fmsGuiGetItem(hwnd, IDC_DRIVER1_ID), gFmsDriver1Id, sizeof(gFmsDriver1Id));
    gFmsDriver1Id[sizeof(gFmsDriver1Id) - 1] = 0;
    GetWindowText(fmsGuiGetItem(hwnd, IDC_DRIVER2_ID), gFmsDriver2Id, sizeof(gFmsDriver2Id));
    gFmsDriver2Id[sizeof(gFmsDriver2Id) - 1] = 0;

    for (i = 0; i < 6; i++)
    {
        gFmsTireLocation[i] = fmsGuiReadHexByte(hwnd, IDC_TIRE_LOCATION_BASE + i);
        gFmsTirePressureKpa[i] = fmsGuiReadUInt(hwnd, IDC_TIRE_PRESSURE_BASE + i, 0, 2500);
        gFmsTireTemperatureC[i] = fmsGuiReadDouble(hwnd, IDC_TIRE_TEMP_BASE + i, -273.0, 1735.0);
    }
    for (i = 0; i < 4; i++)
        fmsGuiReadTellTales(hwnd, IDC_TT_STATUS_BASE + i, gFmsTellTaleStatus[i]);

    if (!gFmsEngineRunning)
    {
        gFmsEngineSpeedRpm = 0.0;
        gFmsActualEnginePercentTorque = 0;
        gFmsEnginePercentLoad = 0;
        gFmsAcceleratorPedalPosition = 0;
    }

    LeaveCriticalSection(&gFmsParamLock);
    fmsGuiApplyTopmost(hwnd);

    sprintf(text, "Applied at %lu ms", GetTickCount());
    SetWindowText(fmsGuiGetItem(hwnd, IDC_STATUS), text);
    fmsGuiRefresh(hwnd);
}

static LRESULT CALLBACK fmsGuiWndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    int controlId;
    int notificationCode;

    switch (msg)
    {
    case WM_CREATE:
        fmsGuiCreateControls(hwnd);
        PcanRuntimeCreateControls(hwnd, 738, 514, 360);
        SetTimer(hwnd, FMS_GUI_TIMER_REFRESH, 250, NULL);
        return 0;

    case WM_COMMAND:
        controlId = LOWORD(wParam);
        notificationCode = HIWORD(wParam);
        if (PcanRuntimeHandleCommand(hwnd, controlId, notificationCode))
            return 0;
        if (controlId == IDC_APPLY && notificationCode == BN_CLICKED)
        {
            fmsGuiApply(hwnd);
            return 0;
        }
        if (controlId == IDC_DEFAULT && notificationCode == BN_CLICKED)
        {
            fmsGuiLoadDefaults(hwnd);
            return 0;
        }
        if (fmsGuiIsCheckControl(controlId) && notificationCode == BN_CLICKED)
        {
            fmsGuiApplyChecks(hwnd);
            fmsGuiRefresh(hwnd);
            return 0;
        }
        break;

    case WM_TIMER:
        if (wParam == FMS_GUI_TIMER_REFRESH)
        {
            fmsGuiRefresh(hwnd);
            PcanRuntimeRefreshStatus(hwnd);
            return 0;
        }
        break;

    case WM_CLOSE:
        DestroyWindow(hwnd);
        return 0;

    case FMS_GUI_WM_SHUTDOWN:
        DestroyWindow(hwnd);
        return 0;

    case WM_DESTROY:
        KillTimer(hwnd, FMS_GUI_TIMER_REFRESH);
        gFmsGuiWindow = NULL;
        PostQuitMessage(0);
        return 0;
    }

    return DefWindowProc(hwnd, msg, wParam, lParam);
}

static DWORD WINAPI fmsGuiThreadProc(LPVOID)
{
    WNDCLASSA wc;
    MSG msg;

    ZeroMemory(&wc, sizeof(wc));
    wc.lpfnWndProc = fmsGuiWndProc;
    wc.hInstance = GetModuleHandle(NULL);
    wc.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.lpszClassName = "FmsJ1939EmulatorWindow";
    RegisterClassA(&wc);

    gFmsGuiWindow = CreateWindowExA(WS_EX_TOPMOST, wc.lpszClassName, "PCAN J1939 Emulator",
        WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX,
        0, 0, 1125, 740, NULL, NULL, wc.hInstance, NULL);

    if (gFmsGuiWindow)
    {
        ShowWindow(gFmsGuiWindow, SW_SHOW);
        UpdateWindow(gFmsGuiWindow);
    }

    while (GetMessage(&msg, NULL, 0, 0) > 0)
    {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    return 0;
}

static void fmsStartGuiThread()
{
    if (gFmsGuiThread)
        return;

    gFmsGuiThread = CreateThread(NULL, 0, fmsGuiThreadProc, NULL, 0, &gFmsGuiThreadId);
}

static void fmsStopGuiThread()
{
    HWND hwnd = gFmsGuiWindow;

    if (hwnd)
        PostMessage(hwnd, FMS_GUI_WM_SHUTDOWN, 0, 0);

    if (gFmsGuiThread)
    {
        WaitForSingleObject(gFmsGuiThread, 2000);
        CloseHandle(gFmsGuiThread);
        gFmsGuiThread = NULL;
        gFmsGuiThreadId = 0;
    }
}

static unsigned long fmsClampU32(double value, double minValue, double maxValue)
{
    if (value < minValue)
        value = minValue;
    if (value > maxValue)
        value = maxValue;
    return (unsigned long)(value + 0.5);
}

static unsigned char fmsClampU8(int value, int minValue, int maxValue)
{
    if (value < minValue)
        value = minValue;
    if (value > maxValue)
        value = maxValue;
    return (unsigned char)value;
}

static int fmsWaveValue(unsigned int tick, unsigned int period, int minValue, int maxValue)
{
    unsigned int pos;
    unsigned int half;
    int span;

    if (period < 2)
        return minValue;

    pos = tick % period;
    half = period / 2;
    span = maxValue - minValue;

    if (pos < half)
        return minValue + (int)((span * pos) / half);

    return maxValue - (int)((span * (pos - half)) / (period - half));
}

static void fmsSetU16(unsigned char* data, int index, unsigned int value)
{
    data[index] = (unsigned char)(value & 0xFF);
    data[index + 1] = (unsigned char)((value >> 8) & 0xFF);
}

static void fmsSetU32(unsigned char* data, int index, unsigned long value)
{
    data[index] = (unsigned char)(value & 0xFF);
    data[index + 1] = (unsigned char)((value >> 8) & 0xFF);
    data[index + 2] = (unsigned char)((value >> 16) & 0xFF);
    data[index + 3] = (unsigned char)((value >> 24) & 0xFF);
}

static unsigned char fmsPackTelltalePair(unsigned char firstStatus, unsigned char secondStatus)
{
    return (unsigned char)(0x88 | (firstStatus & 0x07) | ((secondStatus & 0x07) << 4));
}

static void fmsSetNotAvailable(STCAN_MSG& msg)
{
    for (unsigned int i = 0; i < msg.dlc; i++)
        msg.data[i] = 0xFF;
}

static unsigned int fmsMakeJ1939Id(unsigned char priority, unsigned int pgnOrPfPs, unsigned char sourceAddress)
{
    return (((unsigned int)(priority & 0x07)) << 26) | ((pgnOrPfPs & 0x3FFFF) << 8) | sourceAddress;
}

static void fmsSendCanFrame(unsigned int canId, const unsigned char* data, unsigned char dlc)
{
    STCAN_MSG msg(canId, true, dlc, false);
    unsigned char cluster;

    EnterCriticalSection(&gFmsParamLock);
    cluster = gFmsCluster;
    LeaveCriticalSection(&gFmsParamLock);

    msg.cluster = cluster;
    msg.isExtended = true;
    msg.isRtr = false;
    msg.isCanfd = false;
    msg.dlc = dlc;

    for (unsigned int i = 0; i < dlc && i < 8; i++)
        msg.data[i] = data[i];

    EnterCriticalSection(&gMsgTxLock);
    SendMsg(msg);
    LeaveCriticalSection(&gMsgTxLock);
}

static void fmsSendBamFrom(unsigned int pgn, unsigned char priority, const unsigned char* data, unsigned int dlc, unsigned char sourceAddress)
{
    unsigned char cm[8];
    unsigned char dt[8];
    unsigned int packetCount;
    unsigned int offset;
    unsigned int packet;
    unsigned int i;

    if (dlc == 0)
        return;
    if (dlc > 1785)
        dlc = 1785;

    packetCount = (dlc + 6) / 7;
    if (packetCount > 255)
        packetCount = 255;

    cm[0] = 0x20;
    cm[1] = (unsigned char)(dlc & 0xFF);
    cm[2] = (unsigned char)((dlc >> 8) & 0xFF);
    cm[3] = (unsigned char)(packetCount & 0xFF);
    cm[4] = 0xFF;
    cm[5] = (unsigned char)(pgn & 0xFF);
    cm[6] = (unsigned char)((pgn >> 8) & 0xFF);
    cm[7] = (unsigned char)((pgn >> 16) & 0xFF);
    fmsSendCanFrame(fmsMakeJ1939Id(6, 0x00ECFF, sourceAddress), cm, 8);

    Sleep(100);
    for (packet = 1; packet <= packetCount; packet++)
    {
        dt[0] = (unsigned char)packet;
        offset = (packet - 1) * 7;
        for (i = 0; i < 7; i++)
        {
            if (offset + i < dlc)
                dt[i + 1] = data[offset + i];
            else
                dt[i + 1] = 0xFF;
        }
        fmsSendCanFrame(fmsMakeJ1939Id(6, 0x00EBFF, sourceAddress), dt, 8);
        Sleep(100);
    }
}

static void fmsSendDataFrom(unsigned int pgn, unsigned char priority, const unsigned char* data, unsigned int dlc, unsigned char sourceAddress)
{
    if (dlc <= 8)
    {
        fmsSendCanFrame(fmsMakeJ1939Id(priority, pgn, sourceAddress), data, (unsigned char)dlc);
        return;
    }

    fmsSendBamFrom(pgn, priority, data, dlc, sourceAddress);
}

static void fmsSendData(unsigned int pgn, unsigned char priority, const unsigned char* data, unsigned int dlc)
{
    unsigned char sourceAddress;

    EnterCriticalSection(&gFmsParamLock);
    sourceAddress = gFmsSourceAddress;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSendDataFrom(pgn, priority, data, dlc, sourceAddress);
}

static void fmsSend(unsigned int pgn, unsigned char priority, const unsigned char* data)
{
    fmsSendData(pgn, priority, data, 8);
}

static void fmsSend8(unsigned int pgn, unsigned char priority, unsigned char b0, unsigned char b1, unsigned char b2, unsigned char b3, unsigned char b4, unsigned char b5, unsigned char b6, unsigned char b7)
{
    unsigned char data[8];
    data[0] = b0;
    data[1] = b1;
    data[2] = b2;
    data[3] = b3;
    data[4] = b4;
    data[5] = b5;
    data[6] = b6;
    data[7] = b7;
    fmsSend(pgn, priority, data);
}

static void fmsSendString(unsigned int pgn, unsigned char priority, const char* text)
{
    unsigned char data[1785];
    unsigned int len = 0;

    while (len < sizeof(data) && text[len] != 0)
    {
        data[len] = (unsigned char)text[len];
        len++;
    }

    if (len == 0)
    {
        data[0] = 0xFF;
        len = 1;
    }

    fmsSendData(pgn, priority, data, len);
}

static void fmsSendEEC1()
{
    STCAN_MSG msg(0, true, 8, false);
    int torque;
    double engineSpeed;

    EnterCriticalSection(&gFmsParamLock);
    torque = gFmsActualEnginePercentTorque;
    engineSpeed = gFmsEngineSpeedRpm;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[2] = fmsClampU8(torque + 125, 0, 250);
    fmsSetU16(msg.data, 3, (unsigned int)fmsClampU32(engineSpeed / 0.125, 0, 64255));
    fmsSend(0x00F004, 3, msg.data);
}

static void fmsSendEEC2()
{
    STCAN_MSG msg(0, true, 8, false);
    int accelerator;
    int load;

    EnterCriticalSection(&gFmsParamLock);
    accelerator = gFmsAcceleratorPedalPosition;
    load = gFmsEnginePercentLoad;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[1] = fmsClampU8((int)(accelerator * 2.5 + 0.5), 0, 250);
    msg.data[2] = fmsClampU8(load, 0, 250);
    fmsSend(0x00F003, 3, msg.data);
}

static void fmsSendCCVS()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned int speed;
    unsigned char brakeSwitch;
    unsigned char clutchSwitch;
    unsigned char cruiseControlActive;
    unsigned char ptoState;

    EnterCriticalSection(&gFmsParamLock);
    speed = (unsigned int)fmsClampU32(gFmsWheelBasedSpeedKph * 256.0, 0, 64255);
    brakeSwitch = gFmsBrakeSwitch;
    clutchSwitch = gFmsClutchSwitch;
    cruiseControlActive = gFmsCruiseControlActive;
    ptoState = gFmsPtoState;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU16(msg.data, 1, speed);
    msg.data[3] = (unsigned char)((brakeSwitch & 0x03) | ((clutchSwitch & 0x03) << 2) | ((cruiseControlActive & 0x03) << 4));
    msg.data[7] = (unsigned char)(ptoState & 0x1F);
    fmsSend(0x00FEF1, 6, msg.data);
}

static void fmsSendLFE()
{
    STCAN_MSG msg(0, true, 8, false);
    double fuelRate;
    double fuelEconomy;

    EnterCriticalSection(&gFmsParamLock);
    fuelRate = gFmsFuelRateLph;
    fuelEconomy = gFmsInstantFuelEconomyKmL;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU16(msg.data, 0, (unsigned int)fmsClampU32(fuelRate / 0.05, 0, 64255));
    fmsSetU16(msg.data, 2, (unsigned int)fmsClampU32(fuelEconomy * 512.0, 0, 64255));
    fmsSend(0x00FEF2, 6, msg.data);
}

static void fmsSendCVW()
{
    STCAN_MSG msg(0, true, 8, false);
    double weight;

    EnterCriticalSection(&gFmsParamLock);
    weight = gFmsGrossCombinationVehicleWeightKg;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU16(msg.data, 0, (unsigned int)fmsClampU32(weight / 10.0, 0, 64255));
    fmsSend(0x00FE70, 6, msg.data);
}

static void fmsSendLFC()
{
    STCAN_MSG msg(0, true, 8, false);
    double fuelUsed;

    EnterCriticalSection(&gFmsParamLock);
    fuelUsed = gFmsTotalFuelUsedL;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU32(msg.data, 4, fmsClampU32(fuelUsed / 0.5, 0, 0xFAFFFFFF));
    fmsSend(0x00FEE9, 6, msg.data);
}

static void fmsSendDD()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned char fuelLevel;

    EnterCriticalSection(&gFmsParamLock);
    fuelLevel = gFmsFuelLevel1Percent;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[1] = fmsClampU8((int)(fuelLevel * 2.5 + 0.5), 0, 250);
    fmsSend(0x00FEFC, 6, msg.data);
}

static void fmsSendHOURS()
{
    STCAN_MSG msg(0, true, 8, false);
    double engineHours;

    EnterCriticalSection(&gFmsParamLock);
    engineHours = gFmsEngineHours;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU32(msg.data, 0, fmsClampU32(engineHours / 0.05, 0, 0xFAFFFFFF));
    fmsSend(0x00FEE5, 6, msg.data);
}

static void fmsSendVDHR()
{
    STCAN_MSG msg(0, true, 8, false);
    double distance;

    EnterCriticalSection(&gFmsParamLock);
    distance = gFmsTotalVehicleDistanceKm;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU32(msg.data, 0, fmsClampU32(distance * 1000.0 / 5.0, 0, 0xFAFFFFFF));
    fmsSend(0x00FEC1, 6, msg.data);
}

static void fmsSendTCO1()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned int speed;
    unsigned char motion;
    unsigned char overspeed;
    unsigned char driver1Card;
    unsigned char driver2Card;

    EnterCriticalSection(&gFmsParamLock);
    speed = (unsigned int)fmsClampU32(gFmsTachographSpeedKph * 256.0, 0, 64255);
    motion = gFmsVehicleMotion;
    overspeed = gFmsVehicleOverspeed;
    driver1Card = gFmsDriver1Card;
    driver2Card = gFmsDriver2Card;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = (unsigned char)((motion & 0x03) | ((driver2Card & 0x03) << 2) | ((driver1Card & 0x03) << 4) | ((overspeed & 0x03) << 6));
    fmsSetU16(msg.data, 6, speed);
    fmsSend(0x00FE6C, 6, msg.data);
}

static void fmsSendET1()
{
    STCAN_MSG msg(0, true, 8, false);
    int coolantTemp;
    double oilTemp;
    unsigned int oilTempRaw;

    EnterCriticalSection(&gFmsParamLock);
    coolantTemp = gFmsCoolantTemperatureC;
    oilTemp = gFmsEngineOilTemperatureC;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = fmsClampU8(coolantTemp + 40, 0, 250);
    oilTempRaw = (unsigned int)fmsClampU32((oilTemp + 273.0) / 0.03125, 0, 64255);
    fmsSetU16(msg.data, 2, oilTempRaw);
    fmsSend(0x00FEEE, 6, msg.data);
}

static void fmsSendEBC1()
{
    STCAN_MSG msg(0, true, 8, false);
    double brakePedal;

    EnterCriticalSection(&gFmsParamLock);
    brakePedal = gFmsBrakePedalPositionPercent;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[1] = fmsClampU8((int)(brakePedal / 0.4 + 0.5), 0, 250);
    fmsSend(0x00F001, 6, msg.data);
}

static void fmsSendAMB()
{
    STCAN_MSG msg(0, true, 8, false);
    double ambientTemp;

    EnterCriticalSection(&gFmsParamLock);
    ambientTemp = gFmsAmbientAirTemperatureC;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU16(msg.data, 3, (unsigned int)fmsClampU32((ambientTemp + 273.0) / 0.03125, 0, 64255));
    msg.data[5] = fmsClampU8((int)(ambientTemp + 40.0 + 0.5), 0, 250);
    fmsSend(0x00FEF5, 6, msg.data);
}

static void fmsSendAIR1()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned int pressure1;
    unsigned int pressure2;

    EnterCriticalSection(&gFmsParamLock);
    pressure1 = gFmsServiceBrakeAirPressure1Kpa;
    pressure2 = gFmsServiceBrakeAirPressure2Kpa;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = fmsClampU8((int)(pressure1 / 8), 0, 250);
    msg.data[1] = fmsClampU8((int)(pressure2 / 8), 0, 250);
    fmsSend(0x00FEAE, 6, msg.data);
}

static void fmsSendHRLFC()
{
    STCAN_MSG msg(0, true, 8, false);
    double fuelUsed;

    EnterCriticalSection(&gFmsParamLock);
    fuelUsed = gFmsHighResolutionFuelUsedL;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU32(msg.data, 0, fmsClampU32(fuelUsed / 0.001, 0, 0xFAFFFFFF));
    fmsSend(0x00FD09, 6, msg.data);
}

static void fmsSendAT1T1I()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned char defLevel;

    EnterCriticalSection(&gFmsParamLock);
    defLevel = gFmsDieselExhaustFluidLevelPercent;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = fmsClampU8((int)(defLevel * 2.5 + 0.5), 0, 250);
    fmsSend(0x00FE56, 6, msg.data);
}

static void fmsSendFMS()
{
    unsigned char busMajor;
    unsigned char busMinor;
    unsigned char truckMajor;
    unsigned char truckMinor;

    EnterCriticalSection(&gFmsParamLock);
    busMajor = gFmsBusVersionMajor;
    busMinor = gFmsBusVersionMinor;
    truckMajor = gFmsTruckVersionMajor;
    truckMinor = gFmsTruckVersionMinor;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSend8(0x00FDD1, 6, 0x00, (unsigned char)('0' + busMajor), (unsigned char)('0' + busMinor), (unsigned char)('0' + truckMajor), (unsigned char)('0' + truckMinor), 0xFF, 0xFF, 0xFF);
}

static void fmsSendSERV()
{
    STCAN_MSG msg(0, true, 8, false);
    double serviceDistanceKm;
    long serviceDistance;

    EnterCriticalSection(&gFmsParamLock);
    serviceDistanceKm = gFmsServiceDistanceKm;
    LeaveCriticalSection(&gFmsParamLock);

    serviceDistance = (long)(serviceDistanceKm + (serviceDistanceKm >= 0 ? 0.5 : -0.5));
    fmsSetNotAvailable(msg);
    fmsSetU16(msg.data, 0, (unsigned short)serviceDistance);
    fmsSend(0x00FEC0, 6, msg.data);
}

static void fmsSendPTODE()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned char ptoEngaged;

    EnterCriticalSection(&gFmsParamLock);
    ptoEngaged = gFmsAtLeastOnePtoEngaged;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = (unsigned char)(ptoEngaged & 0x03);
    fmsSend(0x00FDA4, 6, msg.data);
}

static void fmsSendVI()
{
    char vin[18];

    EnterCriticalSection(&gFmsParamLock);
    strncpy(vin, gFmsVin, sizeof(vin));
    vin[sizeof(vin) - 1] = 0;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSendString(0x00FEEC, 6, vin);
}

static void fmsSendTD()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned int year;
    unsigned char month;
    unsigned char day;
    unsigned char hour;
    unsigned char minute;
    unsigned char second;

    EnterCriticalSection(&gFmsParamLock);
    year = gFmsYear;
    month = gFmsMonth;
    day = gFmsDay;
    hour = gFmsHour;
    minute = gFmsMinute;
    second = gFmsSecond;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = fmsClampU8(second * 4, 0, 250);
    msg.data[1] = fmsClampU8(minute, 0, 250);
    msg.data[2] = fmsClampU8(hour, 0, 250);
    msg.data[3] = fmsClampU8(month, 0, 250);
    msg.data[4] = fmsClampU8(day * 4, 0, 250);
    msg.data[5] = fmsClampU8((int)year - 1985, 0, 250);
    fmsSend(0x00FEE6, 6, msg.data);
}

static void fmsSendDC1()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned char frontDoor;
    unsigned char middleDoor;
    unsigned char rearDoor;

    EnterCriticalSection(&gFmsParamLock);
    frontDoor = gFmsFrontDoorOpen;
    middleDoor = gFmsMiddleDoorOpen;
    rearDoor = gFmsRearDoorOpen;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = (unsigned char)((frontDoor & 0x03) | ((middleDoor & 0x03) << 2) | ((rearDoor & 0x03) << 4));
    fmsSend(0x00FE4E, 6, msg.data);
}

static void fmsSendAS()
{
    STCAN_MSG msg(0, true, 8, false);
    double alternatorSpeed;

    EnterCriticalSection(&gFmsParamLock);
    alternatorSpeed = gFmsAlternatorSpeedRpm;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    fmsSetU16(msg.data, 0, (unsigned int)fmsClampU32(alternatorSpeed / 0.125, 0, 64255));
    fmsSend(0x00FED5, 6, msg.data);
}

static void fmsSendFMS1()
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned char blockId;
    unsigned char status[15];
    int i;

    EnterCriticalSection(&gFmsParamLock);
    blockId = gFmsTellTaleBlockId;
    for (i = 0; i < 15; i++)
        status[i] = gFmsTellTaleStatus[blockId & 0x03][i];
    LeaveCriticalSection(&gFmsParamLock);

    fmsSetNotAvailable(msg);
    msg.data[0] = (unsigned char)(0x80 | ((status[0] & 0x07) << 4) | (blockId & 0x0F));
    msg.data[1] = fmsPackTelltalePair(status[1], status[2]);
    msg.data[2] = fmsPackTelltalePair(status[3], status[4]);
    msg.data[3] = fmsPackTelltalePair(status[5], status[6]);
    msg.data[4] = fmsPackTelltalePair(status[7], status[8]);
    msg.data[5] = fmsPackTelltalePair(status[9], status[10]);
    msg.data[6] = fmsPackTelltalePair(status[11], status[12]);
    msg.data[7] = fmsPackTelltalePair(status[13], status[14]);
    fmsSend(0x00FD7D, 6, msg.data);
}

static void fmsSendTIRE1Wheel(int wheelIndex)
{
    STCAN_MSG msg(0, true, 8, false);
    unsigned char enabled;
    unsigned char location;
    unsigned int pressure;

    EnterCriticalSection(&gFmsParamLock);
    enabled = gFmsTpmsEnabled;
    location = gFmsTireLocation[wheelIndex];
    pressure = gFmsTirePressureKpa[wheelIndex];
    LeaveCriticalSection(&gFmsParamLock);

    if (!enabled)
        return;

    fmsSetNotAvailable(msg);
    msg.data[0] = location;
    msg.data[1] = fmsClampU8((int)((pressure + 2) / 4), 0, 250);
    fmsSend(0x00FEF4, 6, msg.data);
}

static void fmsSendTpmsSniffFrame(int wheelIndex, unsigned char pressureFrame)
{
    unsigned char enabled;
    unsigned char sourceAddress;
    unsigned char location;
    unsigned int pressure;
    double temperature;
    unsigned char fe5eIndex;
    unsigned char fe5eMarker;
    unsigned char fec6Status;
    unsigned char data[8];
    unsigned int temperatureRaw;

    EnterCriticalSection(&gFmsParamLock);
    enabled = gFmsTpmsEnabled && gFmsTpmsSniffFramesEnabled;
    sourceAddress = gFmsTpmsSourceAddress;
    location = gFmsTireLocation[wheelIndex];
    pressure = gFmsTirePressureKpa[wheelIndex];
    temperature = gFmsTireTemperatureC[wheelIndex];
    fe5eIndex = gFmsTpmsFe5eIndex[wheelIndex];
    fe5eMarker = gFmsTpmsFe5eMarker[wheelIndex];
    fec6Status = gFmsTpmsFec6Status[wheelIndex];
    LeaveCriticalSection(&gFmsParamLock);

    if (!enabled)
        return;

    if (!pressureFrame)
    {
        temperatureRaw = (unsigned int)fmsClampU32((temperature + 273.0) / 0.03125, 0, 64255);
        data[0] = location;
        fmsSetU16(data, 1, temperatureRaw);
        data[3] = 0xFF;
        data[4] = 0xFF;
        data[5] = 0xFA;
        data[6] = fe5eIndex;
        data[7] = fe5eMarker;
        fmsSendDataFrom(0x00FE5E, 6, data, 8, sourceAddress);
        return;
    }

    data[0] = fec6Status;
    data[1] = location;
    data[2] = 0xFF;
    data[3] = 0xFF;
    data[4] = fmsClampU8((int)((pressure + 5) / 10), 0, 250);
    data[5] = 0xFF;
    data[6] = 0xFF;
    data[7] = 0xFF;
    fmsSendDataFrom(0x00FEC6, 6, data, 8, sourceAddress);
}

static void fmsServiceTpmsTimer100()
{
    static unsigned int tick = 0;
    static unsigned char stage = 0xFF;
    unsigned char wheelIndex;

    tick++;
    if (stage == 0xFF)
    {
        if ((tick % 100) == 30)
            stage = 0;
        else
            return;
    }

    if (stage < 6)
    {
        fmsSendTIRE1Wheel(stage);
    }
    else if (stage < 18)
    {
        wheelIndex = (unsigned char)((stage - 6) / 2);
        fmsSendTpmsSniffFrame(wheelIndex, (unsigned char)((stage - 6) & 0x01));
    }

    stage++;
    if (stage >= 18)
        stage = 0xFF;
}

static void fmsSendDI()
{
    char id[64];
    char driver1[20];
    char driver2[20];
    int pos = 0;
    int i = 0;

    EnterCriticalSection(&gFmsParamLock);
    strncpy(driver1, gFmsDriver1Id, sizeof(driver1));
    driver1[sizeof(driver1) - 1] = 0;
    strncpy(driver2, gFmsDriver2Id, sizeof(driver2));
    driver2[sizeof(driver2) - 1] = 0;
    LeaveCriticalSection(&gFmsParamLock);

    for (i = 0; pos < (int)sizeof(id) - 1 && driver1[i] != 0; i++)
        id[pos++] = driver1[i];
    if (pos < (int)sizeof(id) - 1)
        id[pos++] = '*';
    for (i = 0; pos < (int)sizeof(id) - 1 && driver2[i] != 0; i++)
        id[pos++] = driver2[i];
    if (pos < (int)sizeof(id) - 1)
        id[pos++] = '*';
    id[pos] = 0;

    fmsSendString(0x00FE6B, 6, id);
}

static void fmsUpdateClockLocked()
{
    gFmsClockTick++;
    if (gFmsClockTick < 10)
        return;

    gFmsClockTick = 0;
    gFmsSecond++;
    if (gFmsSecond >= 60)
    {
        gFmsSecond = 0;
        gFmsMinute++;
        if (gFmsMinute >= 60)
        {
            gFmsMinute = 0;
            gFmsHour = (unsigned char)((gFmsHour + 1) % 24);
        }
    }
}

static void fmsUpdateWave()
{
    unsigned int tick = gFmsWaveTick++;

    EnterCriticalSection(&gFmsParamLock);

    if (!gFmsWaveEnabled)
    {
        fmsUpdateClockLocked();
        LeaveCriticalSection(&gFmsParamLock);
        return;
    }

    gFmsEngineSpeedRpm = (double)fmsWaveValue(tick, 240, 650, 2200);
    gFmsActualEnginePercentTorque = fmsWaveValue(tick + 30, 200, 5, 85);
    gFmsEnginePercentLoad = fmsWaveValue(tick + 60, 180, 10, 80);
    gFmsAcceleratorPedalPosition = fmsWaveValue(tick + 20, 160, 0, 70);

    if (!gFmsEngineRunning)
    {
        gFmsEngineSpeedRpm = 0.0;
        gFmsActualEnginePercentTorque = 0;
        gFmsEnginePercentLoad = 0;
        gFmsAcceleratorPedalPosition = 0;
    }

    gFmsWheelBasedSpeedKph = (double)fmsWaveValue(tick, 300, 0, 92);
    gFmsTachographSpeedKph = gFmsWheelBasedSpeedKph;
    gFmsVehicleMotion = (gFmsWheelBasedSpeedKph > 0.5) ? 1 : 0;
    gFmsCruiseControlActive = (gFmsWheelBasedSpeedKph > 45.0 && gFmsWheelBasedSpeedKph < 75.0) ? 1 : 0;
    gFmsBrakeSwitch = ((tick % 300) > 250) ? 1 : 0;
    gFmsClutchSwitch = ((tick % 180) > 165) ? 1 : 0;
    gFmsParkingBrakeSwitch = (gFmsWheelBasedSpeedKph < 0.5) ? 1 : 0;
    gFmsBrakePedalPositionPercent = gFmsBrakeSwitch ? (double)fmsWaveValue(tick + 20, 80, 25, 80) : 0.0;

    gFmsFuelRateLph = 4.0 + gFmsEnginePercentLoad * 0.35;
    gFmsInstantFuelEconomyKmL = 2.0 + gFmsWheelBasedSpeedKph / 60.0;
    gFmsFuelLevel1Percent = fmsClampU8(80 - (int)((tick / 100) % 30), 0, 100);
    gFmsDieselExhaustFluidLevelPercent = fmsClampU8(75 - (int)((tick / 150) % 20), 0, 100);

    gFmsTotalFuelUsedL += gFmsFuelRateLph / 36000.0;
    gFmsHighResolutionFuelUsedL = gFmsTotalFuelUsedL;
    gFmsTotalVehicleDistanceKm += gFmsWheelBasedSpeedKph / 36000.0;
    gFmsEngineHours += 1.0 / 36000.0;

    gFmsCoolantTemperatureC = fmsWaveValue(tick + 40, 260, 78, 94);
    gFmsEngineOilTemperatureC = (double)fmsWaveValue(tick + 80, 320, 82, 104);
    gFmsAmbientAirTemperatureC = (double)fmsWaveValue(tick, 600, 12, 28);
    gFmsServiceBrakeAirPressure1Kpa = (unsigned int)fmsWaveValue(tick, 220, 700, 900);
    gFmsServiceBrakeAirPressure2Kpa = (unsigned int)fmsWaveValue(tick + 25, 220, 700, 900);
    gFmsTirePressureKpa[0] = 900 + (unsigned int)fmsWaveValue(tick + 0, 700, 0, 20);
    gFmsTirePressureKpa[1] = 890 + (unsigned int)fmsWaveValue(tick + 70, 700, 0, 20);
    gFmsTirePressureKpa[2] = 900 + (unsigned int)fmsWaveValue(tick + 140, 700, 0, 20);
    gFmsTirePressureKpa[3] = 890 + (unsigned int)fmsWaveValue(tick + 210, 700, 0, 20);
    gFmsTirePressureKpa[4] = 900 + (unsigned int)fmsWaveValue(tick + 280, 700, 0, 20);
    gFmsTirePressureKpa[5] = 890 + (unsigned int)fmsWaveValue(tick + 350, 700, 0, 20);
    gFmsTireTemperatureC[0] = 15.125 + (double)fmsWaveValue(tick + 0, 500, 0, 5);
    gFmsTireTemperatureC[1] = 15.125 + (double)fmsWaveValue(tick + 60, 500, 0, 5);
    gFmsTireTemperatureC[2] = 15.125 + (double)fmsWaveValue(tick + 120, 500, 0, 5);
    gFmsTireTemperatureC[3] = 15.125 + (double)fmsWaveValue(tick + 180, 500, 0, 5);
    gFmsTireTemperatureC[4] = 15.125 + (double)fmsWaveValue(tick + 240, 500, 0, 5);
    gFmsTireTemperatureC[5] = 15.125 + (double)fmsWaveValue(tick + 300, 500, 0, 5);

    gFmsAtLeastOnePtoEngaged = ((tick % 500) > 420) ? 1 : 0;
    gFmsPtoState = gFmsAtLeastOnePtoEngaged ? 5 : 31;
    gFmsFrontDoorOpen = (gFmsWheelBasedSpeedKph < 0.5 && ((tick / 20) % 2)) ? 1 : 0;
    gFmsMiddleDoorOpen = gFmsFrontDoorOpen;
    gFmsRearDoorOpen = 0;
    gFmsAlternatorSpeedRpm = gFmsEngineSpeedRpm * 2.0;
    gFmsTellTaleBlockId = (unsigned char)((tick / 10) & 0x03);
    gFmsTellTaleStatus[0][6] = gFmsParkingBrakeSwitch ? 1 : 0;
    gFmsTellTaleStatus[0][7] = gFmsBrakeSwitch ? 2 : 0;
    gFmsTellTaleStatus[0][9] = (gFmsFuelLevel1Percent < 58) ? 2 : 0;
    gFmsTellTaleStatus[0][10] = (gFmsCoolantTemperatureC > 90) ? 2 : 0;
    gFmsTellTaleStatus[0][11] = ((tick % 240) > 200) ? 3 : 0;
    gFmsTellTaleStatus[0][12] = ((tick % 360) > 320) ? 1 : 0;
    gFmsTellTaleStatus[1][2] = (gFmsEnginePercentLoad > 70) ? 3 : 0;
    gFmsTellTaleStatus[1][4] = (gFmsEnginePercentLoad > 75) ? 2 : 0;
    gFmsTellTaleStatus[1][6] = gFmsBrakeSwitch ? 3 : 0;
    gFmsTellTaleStatus[1][7] = gFmsBrakeSwitch ? 3 : 0;
    gFmsTellTaleStatus[1][11] = (gFmsCoolantTemperatureC > 88) ? 2 : 0;
    gFmsTellTaleStatus[1][12] = (gFmsEngineSpeedRpm < 750.0) ? 2 : 0;
    gFmsTellTaleStatus[1][13] = (gFmsCoolantTemperatureC > 92) ? 3 : 0;
    gFmsTellTaleStatus[2][0] = gFmsBrakeSwitch ? 2 : 0;
    gFmsTellTaleStatus[2][3] = ((tick % 500) > 420) ? 3 : 0;
    gFmsTellTaleStatus[2][4] = ((tick % 500) > 420) ? 3 : 0;
    gFmsTellTaleStatus[2][10] = (gFmsDieselExhaustFluidLevelPercent < 62) ? 2 : 0;
    gFmsTellTaleStatus[3][1] = ((tick % 300) > 260) ? 3 : 0;
    gFmsTellTaleStatus[3][2] = ((tick % 400) > 350) ? 3 : 0;
    gFmsTellTaleStatus[3][3] = ((tick % 600) > 520) ? 2 : 0;
    gFmsTellTaleStatus[3][7] = gFmsCruiseControlActive ? 3 : 0;
    gFmsTellTaleStatus[3][8] = gFmsAtLeastOnePtoEngaged ? 3 : 0;
    gFmsTellTaleStatus[3][12] = gFmsVehicleOverspeed ? 2 : 0;

    fmsUpdateClockLocked();

    LeaveCriticalSection(&gFmsParamLock);
}

/* Start BUSMASTER generated function - OnDLL_Load */
void OnDLL_Load()
{
    InitializeCriticalSection(&gMsgTxLock);
    InitializeCriticalSection(&gFmsParamLock);
    fmsStartGuiThread();
    Trace("J1939Emulator CAN DLL loaded");
}/* End BUSMASTER generated function - OnDLL_Load */
/* Start BUSMASTER generated function - OnDLL_Unload */
void OnDLL_Unload()
{
    Trace("J1939Emulator CAN DLL unloaded");
    fmsStopGuiThread();
    DeleteCriticalSection(&gFmsParamLock);
    DeleteCriticalSection(&gMsgTxLock);
}/* End BUSMASTER generated function - OnDLL_Unload */
/* Start BUSMASTER generated function - OnTimer_FMS_EEC1_20 */
void OnTimer_FMS_EEC1_20( )
{
    fmsSendEEC1();
}/* End BUSMASTER generated function - OnTimer_FMS_EEC1_20 */
/* Start BUSMASTER generated function - OnTimer_FMS_EEC2_50 */
void OnTimer_FMS_EEC2_50( )
{
    fmsSendEEC2();
    fmsSendEBC1();
    fmsSendTCO1();
}/* End BUSMASTER generated function - OnTimer_FMS_EEC2_50 */
/* Start BUSMASTER generated function - OnTimer_FMS_100 */
void OnTimer_FMS_100( )
{
    fmsSendCCVS();
    fmsSendLFE();
    fmsSendCVW();
    fmsServiceTpmsTimer100();
}/* End BUSMASTER generated function - OnTimer_FMS_100 */
/* Start BUSMASTER generated function - OnTimer_FMS_1000 */
void OnTimer_FMS_1000( )
{
    fmsSendLFC();
    fmsSendDD();
    fmsSendHOURS();
    fmsSendVDHR();
    fmsSendET1();
    fmsSendAMB();
    fmsSendAIR1();
    fmsSendHRLFC();
    fmsSendAT1T1I();
    fmsSendFMS();
    fmsSendSERV();
    fmsSendPTODE();
    fmsSendTD();
    fmsSendDC1();
    fmsSendAS();
    fmsSendFMS1();
}/* End BUSMASTER generated function - OnTimer_FMS_1000 */
/* Start BUSMASTER generated function - OnTimer_FMS_DI_10000 */
void OnTimer_FMS_DI_10000( )
{
    fmsSendVI();
    fmsSendDI();
}/* End BUSMASTER generated function - OnTimer_FMS_DI_10000 */
/* Start BUSMASTER generated function - OnTimer_FMS_WAVE_100 */
void OnTimer_FMS_WAVE_100( )
{
    fmsUpdateWave();
}/* End BUSMASTER generated function - OnTimer_FMS_WAVE_100 */
/* Start BUSMASTER generated function - OnBus_Connect */
void OnBus_Connect()
{
    unsigned char sourceAddress;
    unsigned char addressClaim[8] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80 };

    EnterCriticalSection(&gFmsParamLock);
    sourceAddress = gFmsSourceAddress;
    LeaveCriticalSection(&gFmsParamLock);

    fmsSendCanFrame(fmsMakeJ1939Id(6, 0x00EEFF, sourceAddress), addressClaim, 8);
}/* End BUSMASTER generated function - OnBus_Connect */
